"""Make imported source material read-only at the filesystem level.

`app/core/paths.assert_safe_write_target()` refuses writes into
`source_material/` - but only for code that calls it. Anything writing files
directly (an editor, a PIL `.save()`, a coding agent) bypasses it entirely.

On 2026-07-28 that happened: a subagent writing character identity packages
modified 81 files under `source_material/imported_canon/approved_characters/`.
`python -m app.cli.main validate` caught it via manifest hashes and the files
were restored byte-for-byte from the read-only factory - but the write should
not have been possible.

This sets the OS read-only bit so the next attempt fails at the syscall.

Run after every migration:
    python scripts/migration/import_source_material.py
    python scripts/migration/protect_source_material.py

To edit imported material deliberately (you almost never should - re-run the
migration instead):
    python scripts/migration/protect_source_material.py --unlock
"""

from __future__ import annotations

import argparse
import os
import stat
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]

#: Trees that are immutable copies of an external source of truth.
PROTECTED = (
    REPO_ROOT / "source_material" / "imported_canon",
    REPO_ROOT / "source_material" / "imported_bibles",
    REPO_ROOT / "source_material" / "visual_references",
    REPO_ROOT / "source_material" / "historical_issues",
    REPO_ROOT / "source_material" / "legacy_reference",
)

#: The manifests are regenerated by the migration and must stay writable.
SKIP = {REPO_ROOT / "source_material" / "manifests"}


def set_readonly(path: Path, readonly: bool) -> None:
    mode = path.stat().st_mode
    if readonly:
        path.chmod(mode & ~stat.S_IWRITE & ~stat.S_IWGRP & ~stat.S_IWOTH)
    else:
        path.chmod(mode | stat.S_IWRITE)


def walk(readonly: bool) -> tuple[int, int]:
    changed = 0
    total = 0
    for root in PROTECTED:
        if not root.is_dir():
            continue
        for path in root.rglob("*"):
            if not path.is_file():
                continue
            if any(skip in path.parents for skip in SKIP):
                continue
            total += 1
            writable = os.access(path, os.W_OK)
            if writable == readonly:  # needs flipping
                try:
                    set_readonly(path, readonly)
                    changed += 1
                except OSError as exc:  # pragma: no cover
                    print(f"  ! {path}: {exc}", file=sys.stderr)
    return changed, total


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--unlock", action="store_true",
                        help="make imported material writable again (rarely correct)")
    parser.add_argument("--check", action="store_true",
                        help="report how many imported files are writable, change nothing")
    args = parser.parse_args()

    if args.check:
        writable = 0
        total = 0
        for root in PROTECTED:
            if not root.is_dir():
                continue
            for path in root.rglob("*"):
                if path.is_file():
                    total += 1
                    if os.access(path, os.W_OK):
                        writable += 1
        print(f"{writable} of {total} imported files are writable")
        if writable:
            print("run without --check to protect them")
        return 1 if writable else 0

    readonly = not args.unlock
    changed, total = walk(readonly)
    verb = "protected" if readonly else "unlocked"
    print(f"{verb} {changed} of {total} imported files")
    if readonly:
        print("imported source material is now read-only at the filesystem level")
    else:
        print("WARNING: imported source material is now WRITABLE. Re-protect when done.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
