"""Issue 001 panel data, pages 4-13. See issue001_panels.py for the contract."""

from __future__ import annotations

from scripts.production.build_panel_script import (
    ASH, GROUNDS, LD, MZ, NB, NIGHT, NODE, SC, ST, TT, block, light, panel, say,
)

CROWD = "NEW crowd silhouette set"
LILDEVIL_LAYERS = "NEW Lil Devil alpha layer set - does not exist yet"


def build() -> list[dict]:
    p: list[dict] = []

    # ---------------- PAGE 4 - STATIC FEELS IT (5) ----------------
    p.append(panel(
        4, 1, "Static perceives the fault before any instrument does.",
        "Static stopped dead in a moving crowd, head tilted.",
        GROUNDS, NIGHT, "medium_close", "eye_level", "normal",
        "One still figure in a moving crowd. Motion blur on the crowd, none on him.",
        "Booth row still lit and warm, crowd flowing past in soft silhouette.",
        "Soft moving foreground crowd, Static sharp midground, warm bokeh behind.",
        light("Warm booth lights behind and right", "Amber", "Weak cool ambient",
              "Tight under both feet", rim="Warm edge on hair and shoulder",
              color_spill="Amber on his back"),
        "Still warm, but the warmth is behind him rather than on him.",
        "Upper third, in the empty space above him",
        "tall", "small", "scene_to_scene",
        ["GROUNDS plate A8 - booth row", "character_layers/static", CROWD],
        ["Widow-peak hair and heavy grey eye rings legible",
         "He reads as listening, not frightened", "Crowd motion contrasts his stillness"],
        blocking=[block(ST, "Low and centred, empty space above him", "midground",
                        "Occupies only the lower third of a tall panel",
                        "Both feet, stopped mid-step, weight forward",
                        "Unfocused, angled up and off - listening not looking",
                        "One hand half-raised toward his ear, not touching it",
                        occlusion="A passing crowd silhouette clips his lower edge",
                        expression_id="EXP-003-worried")],
        dialogue=[say(ST, "Something just... stepped down.")],
        foreground_elements=["Passing crowd silhouettes, dark and soft"],
    ))
    p.append(panel(
        4, 2, "Nobody registers anything. His problem is being followed, not being right.",
        "The crowd streams past, entirely unbothered.",
        GROUNDS, NIGHT, "wide", "eye_level", "normal",
        "No identifiable cast. Crowd at three depths.",
        "The booth row from Static's eyeline. People eating, queueing, laughing. Ordinary.",
        "Three crowd depths, booth lights behind.",
        light("Booth lights", "Amber", "Cool ambient", "Overlapping crowd shadows",
              color_spill="Warm on all faces"),
        "Warm and oblivious.", "None - silent panel",
        "wide", "small", "subject_to_subject",
        ["GROUNDS plate A8 wide", CROWD],
        ["Nobody in frame is reacting", "Deliberately unremarkable"],
    ))
    p.append(panel(
        4, 3, "Give the reader the evidence Static hears, before anyone believes him.",
        "Insert on a string of festival bulbs. One dims out of rhythm with the rest.",
        GROUNDS, NIGHT, "insert", "low_angle", "compressed_telephoto",
        "No cast. Object scale.",
        "A run of festival bulbs against dark sky. All steady except one, fading.",
        "Flat and tight. One surface, one anomaly.",
        light("The bulbs themselves", "Warm amber, one fading", "None - dark sky behind",
              "Not applicable", color_spill="Warm falloff around each live bulb"),
        "Warm and almost normal. The anomaly is small enough to miss.",
        "None - silent panel",
        "inset", "small", "aspect_to_aspect",
        ["NEW festival bulb string detail plate"],
        ["Exactly one bulb out of rhythm", "Subtle enough a reader could miss it",
         "The dimming bulb is warm, not cyan - the system has not shown itself"],
    ))
    p.append(panel(
        4, 4, "Static tries to tell someone and cannot make it land.",
        "Static beside Scarline, talking too fast, hands moving.",
        GROUNDS, NIGHT, "two_shot", "eye_level", "normal",
        "Two figures at slightly different depths, one animated and one still.",
        "Path edge, crowd passing behind, booth glow.",
        "Two-plane with crowd behind.",
        light("Booth lights frame left", "Amber", "Cool ambient", "Present under both",
              color_spill="Amber on their left sides"),
        "Warm. The disagreement is not hostile.",
        "Upper left and upper right, reading Static then Scarline",
        "rectangle", "medium", "action_to_action",
        ["GROUNDS plate A8 path edge", "character_layers static, scarline", CROWD],
        ["Static animated and Scarline still - the contrast is the point",
         "She is listening, not dismissing him"],
        blocking=[
            block(ST, "Frame left, animated", "midground", "Reference figure",
                  "Both feet, weight shifting rapidly", "At Scarline, away, back",
                  "Both hands moving, describing a shape", expression_id="EXP-003-determined"),
            block(SC, "Frame right, still, half a step back", "midground", "8 percent smaller",
                  "Both feet, weight settled", "Level at Static", "Arms at sides"),
        ],
        dialogue=[say(ST, "It is stepping down. In order."),
                  say(SC, "Tell NeonBlue. He is nearest the panel.")],
    ))
    p.append(panel(
        4, 5, "End the page on the fault about to arrive, with nobody watching it.",
        "The festival backup panel on a stanchion, indicators green, nobody near it.",
        GROUNDS, NIGHT, "insert", "eye_level", "normal",
        "No cast. Object scale against the stanchion.",
        "The backup panel, weathered, green indicators steady, a service sticker peeling.",
        "Flat. One object, crowd defocused far behind.",
        light("Nearest booth, frame right", "Amber", "Panel indicator glow",
              "Hard shadow under the panel housing",
              color_spill="Weak green from the indicators onto the housing"),
        "Warm, ordinary, ignored. The object NeonBlue will guarantee.",
        "None - silent panel",
        "rectangle", "small", "aspect_to_aspect",
        ["PROP-festival-backup-panel healthy state", "GROUNDS plate A8 defocused"],
        ["All indicators green - it must look capable so its failure lands",
         "Nobody is looking at it", "Green indicators are NOT cyan"],
    ))

    # ---------------- PAGE 5 - THE FIRST BLACKOUT (6) ----------------
    p.append(panel(
        5, 1, "Static reaches NeonBlue, and NeonBlue answers before hearing it.",
        "Static arriving at the food stand, NeonBlue already reassuring him.",
        GROUNDS, NIGHT, "medium", "eye_level", "normal",
        "Two figures across a counter, as on page 3 but reversed.",
        "The food stand counter, quieter now, heat lamps still on.",
        "Counter divides two planes.",
        light("Heat lamps above the counter", "Hot orange", "Cool ambient outside",
              "Present on both", color_spill="Orange on NeonBlue, cooler on Static"),
        "Warm inside, cooling outside.", "Upper centre, two balloons",
        "wide", "medium", "scene_to_scene",
        ["GROUNDS plate A6 counter", "character_layers neonblue, static"],
        ["NeonBlue answers before Static finishes - readable in the body language",
         "Static's urgency is genuine"],
        blocking=[
            block(ST, "Frame left at the counter", "foreground", "Nearer camera",
                  "Both feet, leaning in over the counter", "At NeonBlue",
                  "Both hands flat on the counter", expression_id="EXP-003-worried"),
            block(NB, "Frame right, behind the counter", "midground", "Set back",
                  "Both feet, still working", "At Static, warm",
                  "Still holding an order", expression_id="EXP-005-smile"),
        ],
        dialogue=[say(ST, "The lights are stepping down in order."),
                  say(NB, "Then they will step back up.")],
    ))
    p.append(panel(
        5, 2, "The first blackout. The moment the issue turns.",
        "The booth row behind NeonBlue drops dark, left to right, mid-sentence.",
        GROUNDS, NIGHT, "medium", "eye_level", "normal",
        "Single figure with the failure happening behind and past him.",
        "The booth row receding to frame left, going dark in sequence. The backup panel beside him, indicators dead.",
        "NeonBlue foreground right, darkness travelling into the midground, a few lit stalls far behind.",
        light("The last working light, frame right and low", "Warm amber, dying",
              "Almost none - fill collapses as the row goes out",
              "Present, lengthening as the key weakens",
              color_spill="Warm on his raised hand, which stays lit longest"),
        "Amber losing to darkness left to right. His hand is the last warm thing.",
        "Upper left, over the darkening booths",
        "wide", "large", "action_to_action",
        ["GROUNDS plate A8 lights-failing variant", "character_layers/neonblue",
         "PROP-festival-backup-panel dead state"],
        ["The blackout is visibly IN PROGRESS, not already complete",
         "His raised hand is the brightest element",
         "His expression is confident - the failure is behind him",
         "Backup panel indicators visibly dead"],
        blocking=[block(NB, "Foreground right, three-quarter to camera", "foreground",
                        "Head roughly a quarter of panel height",
                        "Both feet planted, weight even, mid-gesture",
                        "Off to the crowd frame left, not at the failing lights",
                        "One hand raised palm-out, fingers spread",
                        expression_id="EXP-005-smile")],
        dialogue=[say(NB, "Completely normal. Backup comes up in three, two -")],
        sfx=["tk"],
    ))
    p.append(panel(
        5, 3, "The backup does not come. The promise fails in public.",
        "Total dark on the booth row. Nothing happens.",
        GROUNDS, NIGHT, "wide", "eye_level", "normal",
        "Figures reduced to silhouette. Scale from the booth structures.",
        "The booth row, dark. Shapes only. A few phone lights coming up in the crowd.",
        "Silhouette foreground, dark midground, distant lit festival behind.",
        light("Distant festival glow only", "Cool residual", "None",
              "Not readable in this light",
              color_spill="Faint cool edge on the nearest shapes"),
        "The first genuinely dark panel. The contrast with page 3 panel 5 should hurt.",
        "None - silent panel",
        "wide", "medium", "moment_to_moment",
        ["GROUNDS plate A8 blackout state", CROWD],
        ["Genuinely dark - do not lift exposure to make it readable",
         "Phone lights coming up in the crowd", "Silent"],
    ))
    p.append(panel(
        5, 4, "NeonBlue keeps going. The reassurance is visibly for him, not them.",
        "NeonBlue in the dark, still smiling, hand still raised.",
        GROUNDS, NIGHT, "close", "eye_level", "compressed_telephoto",
        "Tight single, mostly dark.",
        "Near-black. Only a phone light from below picks him out.",
        "Shallow, dark.",
        light("A crowd phone light from below and left", "Cool white", "Almost none",
              "Not applicable",
              color_spill="Hard cool underlight on his jaw and the underside of his brow"),
        "Cold underlight. The first unflattering light on him in the issue.",
        "Upper right",
        "rectangle", "small", "action_to_action",
        ["character_layers/neonblue close-crop", "GROUNDS plate A8 blackout"],
        ["Underlight is unflattering and deliberate",
         "The smile is unchanged - that is what makes it uncomfortable",
         "Under-eye bags heavily shadowed"],
        blocking=[block(NB, "Centre, close, lit from below", "foreground",
                        "Head fills half the panel", "Not visible", "Off at the crowd",
                        "Hand still raised at the frame edge", expression_id="EXP-005-smile")],
        dialogue=[say(NB, "Any second now.")],
        approach="approved_layer_composite",
    ))
    p.append(panel(
        5, 5, "Moodz says the quiet thing first, and gently.",
        "Moodz arriving beside him in the dark.",
        GROUNDS, NIGHT, "two_shot", "eye_level", "normal",
        "Two figures in low light at slightly different depths.",
        "Dark booth row, crowd phone lights scattered behind.",
        "Two-plane, both dim, scattered points of light behind.",
        light("Scattered crowd phone lights", "Cool white, several directions", "None",
              "Faint, multiple, soft", color_spill="Cool from several angles, no single key"),
        "Cold and scattered. Nobody has control of the light.",
        "Upper centre",
        "rectangle", "medium", "subject_to_subject",
        ["GROUNDS plate A8 blackout", "character_layers neonblue, moodz"],
        ["Multiple weak sources give multiple faint shadows", "Moodz is not accusing him"],
        blocking=[
            block(MZ, "Frame left, arriving", "midground", "Reference figure",
                  "Both feet, stopping", "At NeonBlue", "Hands in pockets"),
            block(NB, "Frame right", "midground", "Level with Moodz",
                  "Both feet, weight even", "Ahead at the dark, not at Moodz",
                  "Hand finally lowering"),
        ],
        dialogue=[say(MZ, "It is not coming up.")],
    ))
    p.append(panel(
        5, 6, "Close on NeonBlue committing to fix it - his strength and his flaw at once.",
        "NeonBlue turning and moving, decisive, in the wrong direction.",
        GROUNDS, NIGHT, "medium_wide", "low_angle", "normal",
        "Single figure moving away, crowd shapes around.",
        "Dark grounds, NeonBlue moving toward the distant lit section.",
        "Figure midground moving away, dark crowd foreground, lit festival far behind.",
        light("Distant lit section ahead of him", "Warm amber, far", "Cool residual",
              "Faint under his feet", rim="Warm rim on his front edge",
              color_spill="Warm ahead, cold behind"),
        "He is walking toward the light. The story is in the other direction.",
        "Upper right",
        "wide", "medium", "action_to_action",
        ["GROUNDS plate A8 blackout wide", "character_layers/neonblue", CROWD],
        ["He moves toward the LIT part - thematically wrong, deliberately",
         "Warm ahead and cold behind must both read"],
        blocking=[block(NB, "Centre, moving away from camera", "midground", "Mid-scale",
                        "Both feet, purposeful stride", "Ahead at the lit section",
                        "Arms swinging, moving fast", expression_id="EXP-005-determined")],
        dialogue=[say(NB, "Then we find the panel that did it.")],
    ))

    # ---------------- PAGE 6 - SCARLINE (4) ----------------
    p.append(panel(
        6, 1, "Show the crowd's reaction as the actual developing hazard.",
        "The crowd in the dark section beginning to move the wrong way.",
        GROUNDS, NIGHT, "wide", "high_angle", "normal",
        "No identifiable cast. Crowd flow is the subject.",
        "Dark grounds from above. Two crowd currents meeting and jamming at a narrow point between stalls.",
        "Single deep plane from above. Depth from crowd density and phone-light scatter.",
        light("Scattered phone lights within the crowd", "Cool white",
              "Distant warm from the lit section", "Not readable at this scale",
              color_spill="Points of cool light through a dark mass"),
        "Dark and granular. The danger is people, not the dark.",
        "None - silent panel",
        "wide", "medium", "scene_to_scene",
        ["NEW GROUNDS plate A9 - crowd jam from above, blackout", CROWD],
        ["The jam point is legible", "Crowd reads as individuals despite the dark",
         "This is the hazard Scarline names next"],
    ))
    p.append(panel(
        6, 2, "Scarline names the real danger. One clear sentence, delivered once.",
        "Scarline watching the jam, unmoved by it.",
        GROUNDS, NIGHT, "medium", "eye_level", "normal",
        "Single figure with the crowd jam behind her.",
        "The narrow point between stalls, crowd pressing, seen past her shoulder.",
        "Scarline midground sharp, crowd jam behind at two depths.",
        light("Scattered phone lights behind", "Cool white", "Distant warm",
              "Faint under her feet",
              rim="Cool rim from behind, separating her from the crowd",
              color_spill="Cool on her back and shoulders"),
        "Cold and clear. She is the calmest thing in frame.",
        "Upper left",
        "rectangle", "medium", "subject_to_subject",
        ["GROUNDS plate A9 ground level", "character_layers/scarline", CROWD],
        ["Scarlet streak legible in low light - required canon",
         "She is calm, not cold", "Line delivered once, not repeated"],
        blocking=[block(SC, "Frame left, side-on, foreground of the jam", "midground",
                        "Head roughly a third of panel height",
                        "Both feet, weight settled, deliberately still",
                        "At the crowd jam, assessing", "Arms at sides")],
        dialogue=[say(SC, "Dark is not the problem. What people do in it is.")],
    ))
    p.append(panel(
        6, 3, "The team can work without NeonBlue directing.",
        "TwoTone hauling a stall barrier open while Scarline waves people through.",
        GROUNDS, NIGHT, "medium_wide", "eye_level", "normal",
        "Two working figures with crowd flowing between and past them.",
        "A stall barrier swung open, crowd starting to move through the new gap.",
        "Crowd foreground, the two working midground, jam relieving behind.",
        light("Phone lights and one stall emergency lamp", "Cool white and weak amber",
              "None", "Present under both", color_spill="Mixed and weak"),
        "Dark and practical. Work being done.",
        "Upper right",
        "wide", "medium", "action_to_action",
        ["GROUNDS plate A9 barrier", "character_layers twotone, scarline", CROWD],
        ["Both are physically working, not standing",
         "The barrier movement is believable", "Crowd responds to the new gap"],
        blocking=[
            block(TT, "Frame left, hauling the barrier", "midground", "Reference figure",
                  "Both feet braced, weight pulling backward", "At the barrier hinge",
                  "Both hands on the barrier rail"),
            block(SC, "Frame right, at the new gap", "midground", "Level with TwoTone",
                  "Both feet, weight even", "At the oncoming crowd",
                  "One arm extended, directing flow"),
        ],
        dialogue=[say(TT, "Give them somewhere to go.")],
    ))
    p.append(panel(
        6, 4, "Extend the fault beyond one section - this is spreading.",
        "A second, distant section of the festival goes dark.",
        GROUNDS, NIGHT, "extreme_wide", "eye_level", "compressed_telephoto",
        "No cast. Two dark zones and one lit one.",
        "Across the grounds. One section already dark. A second, further away, going out now.",
        "Compressed. Foreground dark, midground lit, background going dark.",
        light("The remaining lit section", "Amber", "None on the dark zones",
              "Not applicable", color_spill="Warm confined to the shrinking lit band"),
        "Two darks squeezing one warm band. The pattern is visible before it is named.",
        "None - silent panel",
        "wide", "small", "aspect_to_aspect",
        ["NEW GROUNDS plate A10 - two dark zones, compressed"],
        ["Two separate dark zones clearly distinguishable",
         "The lit band between them is visibly narrowing", "Silent"],
    ))

    # ---------------- PAGE 7 - IT SPREADS (7, DENSE) ----------------
    p.append(panel(
        7, 1, "Open the dense page with a fast beat - a ride stopping.",
        "A ride halting mid-turn, gondolas swinging.",
        GROUNDS, NIGHT, "medium", "low_angle", "normal",
        "No cast. Ride structure against sky.",
        "A fairground ride stopped at an odd angle, gondolas swinging, lights dead.",
        "Ride structure midground against night sky.",
        light("Distant festival glow", "Weak amber", "Night sky", "Not applicable",
              color_spill="Faint warm on the ride's near edges"),
        "Dark and wrong. Machinery in a state it should not be in.",
        "Upper right",
        "rectangle", "small", "scene_to_scene",
        ["NEW GROUNDS plate A11 - stopped ride, low"],
        ["The stop angle is visibly not a resting position", "Gondolas mid-swing"],
        sfx=["kk-CHUNK"],
    ))
    p.append(panel(
        7, 2, "A fast reaction beat from the public.",
        "Faces in the ride queue looking up.",
        GROUNDS, NIGHT, "medium_wide", "low_angle", "normal",
        "No cast. Crowd faces.",
        "A queue of festival-goers looking up at the stopped ride, lit by their own phones.",
        "Shallow. One row of faces.",
        light("Phone screens from below", "Cool white", "None", "Not applicable",
              color_spill="Hard cool underlight on every face"),
        "Cold underlight on a row of ordinary faces.",
        "None - silent panel",
        "wide", "small", "action_to_action",
        [CROWD + " - upward-looking faces variant"],
        ["Faces read as individuals", "Underlight consistent across all of them",
         "Nobody is panicking yet"],
    ))
    p.append(panel(
        7, 3, "A fast reaction beat from the cast.",
        "Static, hands over his ears, in the dark.",
        GROUNDS, NIGHT, "close", "eye_level", "normal",
        "Tight single.", "Near-black behind him.", "Shallow, dark.",
        light("Weak scattered phone light", "Cool white", "None", "Not applicable",
              color_spill="Faint cool on one cheek"),
        "Dark and tight. Overload beginning.",
        "Upper left",
        "square", "small", "subject_to_subject",
        ["character_layers/static close-crop"],
        ["Overload, not panic - he is still functioning", "This is not played for comedy"],
        blocking=[block(ST, "Centre, close", "foreground", "Head fills the panel",
                        "Not visible", "Squeezed shut", "Both hands over his ears",
                        expression_id="EXP-003-shocked")],
        dialogue=[say(ST, "It is getting louder.", "whisper")],
        approach="approved_layer_composite",
    ))
    p.append(panel(
        7, 4, "The festival's own systems fail to cope.",
        "A staff member hammering an unresponsive control box.",
        GROUNDS, NIGHT, "medium_close", "eye_level", "normal",
        "One background-character figure, hands as the focus.",
        "A festival staff control box, screen dead, a gloved hand striking it.",
        "Shallow, hands and box.",
        light("A hand torch held awkwardly", "Cool white", "None",
              "Hard shadow of the hand on the box face",
              color_spill="Cool on the box housing"),
        "Cold, functional, futile.",
        "None - silent panel",
        "rectangle", "small", "action_to_action",
        [CROWD + " - staff figure", "NEW festival staff control box prop"],
        ["Hands are the focus and must be believable",
         "Torch shadow is hard and directional",
         "This is NOT the control-node box from page 13"],
        sfx=["thd thd"],
    ))
    p.append(panel(
        7, 5, "Place Ash somewhere useful and quiet.",
        "Ash guiding two lost children by walking slowly and letting them follow.",
        GROUNDS, NIGHT, "medium", "eye_level", "normal",
        "One cast figure and two small extras at a shallower depth.",
        "A dark path, distant lit section ahead as a destination.",
        "Ash midground, two small figures just behind, lit section far behind.",
        light("Distant lit section ahead", "Warm amber, far", "Cool residual",
              "Faint under all three", rim="Warm front rim on all three",
              color_spill="Warm ahead"),
        "Dark with a warm destination. Quietly hopeful.",
        "None - silent panel",
        "rectangle", "small", "subject_to_subject",
        ["GROUNDS plate A8 dark path", "character_layers/ash", CROWD + " - two child figures"],
        ["Ash is not talking to them - he is walking slowly",
         "The two children are distinct from each other", "Silent"],
        blocking=[block(ASH, "Centre, walking away at an angle", "midground",
                        "Reference figure", "Both feet, deliberately slow",
                        "Ahead at the lit section", "Hands out of pockets, at his sides")],
    ))
    p.append(panel(
        7, 6, "NeonBlue starts making promises to strangers.",
        "NeonBlue crouched to a worried festival-goer's height, reassuring.",
        GROUNDS, NIGHT, "medium_close", "eye_level", "normal",
        "One crouched cast figure and one standing extra, heights deliberately matched.",
        "Dark path edge, a food stall emergency lamp behind.",
        "Two figures midground, dark beyond.",
        light("A single emergency lamp frame right", "Weak amber", "Cool ambient",
              "Present under both, hard-edged", color_spill="Amber on their right sides"),
        "One small warm source in a lot of dark.",
        "Upper left",
        "rectangle", "medium", "subject_to_subject",
        ["GROUNDS plate A8 path edge", "character_layers/neonblue",
         CROWD + " - worried adult figure"],
        ["Crouching to match height reads as kindness, and it is",
         "The promise he makes is one he cannot keep",
         "Contact shadows on both, from one hard source"],
        blocking=[block(NB, "Frame left, crouched", "midground",
                        "Crouched to match the extra's eyeline",
                        "One knee down, one foot flat", "Level at the festival-goer",
                        "One hand on his own knee, one gesturing",
                        expression_id="EXP-005-smile")],
        dialogue=[say(NB, "They will have it back before the finale.")],
    ))
    p.append(panel(
        7, 7, "Close the dense page on the scale of it.",
        "Wide across the grounds. Two dark zones have grown and nearly meet.",
        GROUNDS, NIGHT, "extreme_wide", "high_angle", "wide_distorted",
        "No cast. Dark and light zones are the subject.",
        "The grounds from a raised angle. Two large dark regions with a narrowing lit corridor between them.",
        "Single deep plane. Depth from light density.",
        light("Remaining lit zones", "Amber", "Night sky", "Not applicable at this scale",
              color_spill="Warm glow bleeding into haze above the lit band"),
        "A map made of light. The dark is winning and has a shape.",
        "None - silent panel",
        "wide", "large", "aspect_to_aspect",
        ["NEW GROUNDS plate A12 - two dark zones nearly meeting, high wide"],
        ["The two zones are visibly converging", "The lit corridor is narrow",
         "Sets up page 11 - do not reveal the full pattern yet"],
    ))

    # ---------------- PAGE 8 - TWOTONE MAPS IT (5) ----------------
    p.append(panel(
        8, 1, "TwoTone starts working the problem the way only he does.",
        "TwoTone at a festival map board, hand flat on it.",
        GROUNDS, NIGHT, "medium", "eye_level", "normal",
        "Single figure at a lit board.",
        "A backlit festival map board, one of the few things still powered.",
        "Figure and board midground, dark grounds behind.",
        light("The board itself, frontal", "Cool white", "None",
              "His shadow thrown back onto the ground behind him",
              color_spill="Cool white on his front, nothing on his back"),
        "Clinical. The only clean light in several pages.",
        "Upper right",
        "rectangle", "medium", "scene_to_scene",
        ["NEW festival map board prop", "character_layers/twotone"],
        ["Lit from the front by the board, dark behind - strong silhouette read",
         "Half-black half-white hair works with the frontal light"],
        blocking=[block(TT, "Frame left, side-on to the board", "midground",
                        "Board is roughly 1.4 character heights",
                        "Both feet, weight forward onto the board", "At the board",
                        "One hand flat against the map")],
        dialogue=[say(TT, "Show me where.")],
    ))
    p.append(panel(
        8, 2, "The insert that carries the page's information.",
        "Close on the board. Two fingers tracing two separate paths.",
        GROUNDS, NIGHT, "insert", "high_angle", "normal",
        "Hands and board. The figure is secondary.",
        "The festival map, two areas visibly marked dark, two fingers tracing curving paths toward the centre.",
        "Shallow. Board surface and hands.",
        light("The board, from within", "Cool white", "None",
              "Hand shadows falling on the board face", color_spill="Cool on his palms"),
        "Cool and diagrammatic.",
        "Upper right",
        "rectangle", "small", "aspect_to_aspect",
        ["NEW festival map board prop, marked-dark state", "character_layers/twotone hands"],
        ["The two traced paths are legible and clearly converging",
         "Hand shadows land correctly on the board surface",
         "Board carries no readable text"],
        blocking=[block(TT, "Hands only, entering from frame bottom", "foreground",
                        "Hands near life scale on the board", "Standing, out of frame",
                        "Not visible", "Two fingers tracing two separate curving paths")],
        dialogue=[say(TT, "Two failures. Different directions. Same speed.")],
    ))
    p.append(panel(
        8, 3, "NeonBlue reaches for the comforting reading.",
        "NeonBlue at TwoTone's shoulder, looking at the board.",
        GROUNDS, NIGHT, "two_shot", "eye_level", "normal",
        "Two figures at the board, one nearer.",
        "The board from behind and to one side, its glow on both faces.",
        "Two-plane, both lit by the board.",
        light("The board, frontal on both", "Cool white", "None",
              "Both shadows thrown back away from the board",
              color_spill="Cool white on both faces, nothing behind"),
        "Cool and shared. Two people looking at the same fact.",
        "Upper left and upper right",
        "rectangle", "medium", "action_to_action",
        ["NEW festival map board prop", "character_layers neonblue, twotone"],
        ["Both faces lit identically by one source",
         "NeonBlue's reading is hopeful and wrong"],
        blocking=[
            block(NB, "Frame right, nearer camera", "foreground", "8 percent larger",
                  "Both feet, leaning in", "At the board", "One hand on the board frame",
                  expression_id="EXP-005-thinking"),
            block(TT, "Frame left, at the board", "midground", "Reference figure",
                  "Both feet, weight forward", "At the board", "Fingers still on the map"),
        ],
        dialogue=[say(NB, "So it is two faults."), say(TT, "Or one thing, doing two things.")],
    ))
    p.append(panel(
        8, 4, "Lil Devil reappears with the shortest possible solution.",
        "Lil Devil arriving at the board, uninterested in the map.",
        GROUNDS, NIGHT, "medium", "eye_level", "normal",
        "Single figure entering from dark into the board light.",
        "Edge of the board's light pool, dark beyond.",
        "Figure crossing from dark background into lit midground.",
        light("The board, frame left", "Cool white", "None",
              "Hard-edged as he enters the light pool",
              rim="Cool rim on his leading edge",
              color_spill="Cool white on his left, black on his right"),
        "Half-lit. Red against cool white.",
        "Upper right",
        "rectangle", "small", "subject_to_subject",
        [LILDEVIL_LAYERS, "NEW festival map board prop light pool"],
        ["Half-lit split is hard-edged, matching house-style cel shading",
         "He does not look at the map"],
        blocking=[block(LD, "Frame right, entering the light pool", "midground",
                        "Reference figure", "Both feet, walking in",
                        "At the two of them, not the board", "Hands loose, flexing")],
        dialogue=[say(LD, "Or we open the box it is coming from.")],
    ))
    p.append(panel(
        8, 5, "Point everyone at the control node, setting up pages 12 and 13.",
        "The three looking off toward the service area, board light behind them.",
        GROUNDS, NIGHT, "medium_wide", "low_angle", "normal",
        "Three figures at three depths, all facing the same off-frame direction.",
        "The board behind them, the dark service area ahead off frame right.",
        "Board glow behind, three figures midground, darkness ahead.",
        light("Board from behind", "Cool white", "None ahead of them",
              "Long shadows thrown forward toward the dark",
              rim="Cool rim on all three from behind",
              color_spill="Cool on their backs, nothing on their faces"),
        "Backlit. All three facing into the dark.",
        "Upper left",
        "wide", "medium", "action_to_action",
        ["NEW festival map board prop", "character_layers neonblue, twotone", LILDEVIL_LAYERS],
        ["All three shadows point the same way, into the dark",
         "Faces are unlit - deliberate", "Three distinct silhouettes"],
        blocking=[
            block(NB, "Centre", "midground", "Reference figure", "Both feet, turning",
                  "Off frame right into the dark", "Arms at sides"),
            block(TT, "Frame left, slightly behind", "midground", "6 percent smaller",
                  "Both feet", "Same direction", "Neutral at sides"),
            block(LD, "Frame right, slightly ahead", "foreground", "8 percent larger",
                  "Both feet, already leaning that way", "Same direction", "Hands flexing"),
        ],
        dialogue=[say(NB, "Service side. Both paths start there.")],
    ))

    # ---------------- PAGE 9 - THE PULSE (6) ----------------
    p.append(panel(
        9, 1, "Static's perception becomes something the reader can see.",
        "The public projection screen, image intact but flickering.",
        GROUNDS, NIGHT, "wide", "eye_level", "normal",
        "No cast. The screen and its stanchions.",
        "A large public projection screen on the grounds, image beginning to break up.",
        "Screen midground, dark grounds foreground and behind.",
        light("The screen", "Cool white with colour breakup", "None",
              "Screen light pooling on the ground below it",
              color_spill="Screen colours on the nearest ground and stanchions"),
        "Cool and unstable.", "None - silent panel",
        "wide", "small", "scene_to_scene",
        ["PROP-public-projection-screen breaking-up state"],
        ["Breakup is beginning, not complete", "No cyan geometry yet - that is panel 3"],
    ))
    p.append(panel(
        9, 2, "Static arrives at the screen, drawn by what he can hear.",
        "Static walking toward the screen, others walking away from it.",
        GROUNDS, NIGHT, "medium_wide", "eye_level", "normal",
        "One cast figure moving against a crowd current.",
        "The screen ahead, crowd moving past him in the opposite direction.",
        "Crowd foreground moving one way, Static midground moving the other, screen behind.",
        light("The screen ahead of him", "Cool white", "Scattered phone light",
              "Present under him and the nearest crowd",
              rim="Cool rim on his front edge", color_spill="Cool ahead, nothing behind"),
        "Cold, and he is the only one going toward it.",
        "Upper right",
        "wide", "medium", "action_to_action",
        ["PROP-public-projection-screen", "character_layers/static", CROWD],
        ["He moves against the crowd current - the composition must make that obvious",
         "Lit from ahead, dark behind"],
        blocking=[block(ST, "Centre, moving away from camera toward the screen", "midground",
                        "Mid-scale", "Both feet, walking steadily", "At the screen",
                        "One hand near his ear",
                        occlusion="Crowd silhouettes cross in front of him",
                        expression_id="EXP-003-determined")],
    ))
    p.append(panel(
        9, 3, "The cyan fracture. Seed the six tones and put the reveal on the page.",
        "The screen has fractured into hard cyan geometric shards. Static's reflection in the glass.",
        GROUNDS, NIGHT, "insert", "eye_level", "normal",
        "Character present only as a reflection. The screen is the subject.",
        "The projection screen fills the frame. Its image has broken into hard-edged cyan geometric shards with dark gaps between them.",
        "Flat by design - screen surface, with the reflection as one shallow depth cue.",
        light("The screen is the light source", "Hard cyan", "None", "Not applicable",
              color_spill="Cyan on the reflected figure"),
        "Cyan dominant and cold. First time cyan is the loudest thing in a panel.",
        "Lower right, over a dark gap between shards",
        "rectangle", "medium", "aspect_to_aspect",
        ["PROP-public-projection-screen fractured-cyan state", "character_layers/static reflection"],
        ["The cyan fracture is unmistakably present in the artwork",
         "SIX discrete elements are countable in the shard arrangement",
         "The reflection reads as a reflection, not a composited figure",
         "Screen shows no readable text"],
        blocking=[block(ST, "Visible only as a reflection in the screen glass, lower left",
                        "foreground", "Reflection at half the apparent size of the screen content",
                        "Not visible - reflection only", "Up at the screen", "Not visible",
                        occlusion="Screen content overlays his reflection")],
        dialogue=[say(ST, "It is not noise. It is six things, over and over.")],
        sfx=["hmmm - hmmm - hmmm"],
    ))
    p.append(panel(
        9, 4, "Confirm Static is right by showing a second screen doing the same thing.",
        "A smaller screen elsewhere showing the identical cyan shards.",
        GROUNDS, NIGHT, "insert", "low_angle", "compressed_telephoto",
        "No cast. Object only.",
        "A smaller information screen on a stanchion, carrying the identical cyan shard pattern.",
        "Flat and tight.",
        light("The screen", "Hard cyan", "None", "Not applicable",
              color_spill="Cyan on the stanchion housing"),
        "Cyan, identical, repeated. It is a pattern, not a fault.",
        "None - silent panel",
        "inset", "small", "aspect_to_aspect",
        ["PROP-public-projection-screen fractured-cyan, small variant"],
        ["The shard pattern is IDENTICAL to the previous panel - that is the point",
         "Six countable elements again"],
    ))
    p.append(panel(
        9, 5, "NeonBlue sees it and reaches for a technical explanation.",
        "NeonBlue looking up at the fractured screen, cyan on his face.",
        GROUNDS, NIGHT, "medium_close", "low_angle", "normal",
        "Single figure lit hard by the screen above him.",
        "The screen above and behind, dark grounds around.",
        "Figure foreground, screen behind and above.",
        light("The screen, from above and ahead", "Hard cyan", "Almost none",
              "Hard shadow thrown down and back",
              color_spill="Cyan across his upturned face, catching his under-eye bags"),
        "Cyan on the character whose own colour is cyan. Deliberately uncomfortable.",
        "Upper left",
        "rectangle", "medium", "subject_to_subject",
        ["PROP-public-projection-screen fractured-cyan", "character_layers/neonblue"],
        ["Screen cyan and his own crown cyan must be distinguishable in hue",
         "Upturned face lit from above",
         "First time the system's colour is ON him"],
        blocking=[block(NB, "Centre, looking up", "foreground",
                        "Head fills a third of the panel", "Both feet, head tilted back",
                        "Up at the screen", "One hand shielding his eyes from the screen",
                        expression_id="EXP-005-confused")],
        dialogue=[say(NB, "That is a signal fault. That is all that is.")],
    ))
    p.append(panel(
        9, 6, "Close the page with Static stating the thing nobody wants to hear.",
        "Static beside him, not looking at the screen, listening instead.",
        GROUNDS, NIGHT, "close", "eye_level", "normal",
        "Tight single with cyan from off-frame.",
        "Dark, with cyan spill from the screen off frame left.",
        "Shallow.",
        light("Screen from off frame left", "Hard cyan", "None", "Not applicable",
              color_spill="Cyan edge on his left profile only"),
        "Cyan edge on black. Minimal.",
        "Upper right",
        "square", "small", "action_to_action",
        ["character_layers/static close-crop"],
        ["Eyes closed or averted - he is listening, not looking",
         "Cyan touches only his edge", "He is right"],
        blocking=[block(ST, "Centre, profile", "foreground", "Head fills the panel",
                        "Not visible", "Closed or averted - listening", "Not visible",
                        expression_id="EXP-003-worried")],
        dialogue=[say(ST, "It is not broadcasting. It is asking.")],
        approach="approved_layer_composite",
    ))

    # ---------------- PAGE 10 - THE CRACK (5) ----------------
    p.append(panel(
        10, 1, "NeonBlue's brightness gets louder as the situation gets worse.",
        "NeonBlue herding people toward the lit section, mid-laugh, too wide.",
        GROUNDS, NIGHT, "medium", "eye_level", "normal",
        "One figure among extras who are ignoring him.",
        "A dark stretch of the grounds, people moving past toward the still-lit areas.",
        "Dark occluding foreground, NeonBlue midground, dim grounds behind.",
        light("Remaining festival lights frame left", "Warm amber, thin", "Cool ambient night",
              "Present but weakening", color_spill="Amber on his left side only"),
        "The warmth is running out. His performance is brighter than the light on him.",
        "Upper right, clear of the crowd silhouettes",
        "rectangle", "medium", "scene_to_scene",
        ["GROUNDS plate A8 variant", "character_layers/neonblue", CROWD],
        ["No crowd figure is looking at him",
         "Foreground occlusion is genuine, not a pasted overlay",
         "Effortful brightness, never foolishness"],
        blocking=[block(NB, "Centre midground, arms wide", "midground",
                        "Head roughly a quarter of panel height",
                        "Both feet, weight up on the balls, leaning into the gesture",
                        "At the crowd, who are not returning it", "Both arms wide, herding",
                        occlusion="Foreground crowd silhouettes cross his lower body",
                        expression_id="EXP-005-laughing")],
        dialogue=[say(NB, "This way. Best view is over here anyway.", "shout")],
    ))
    p.append(panel(
        10, 2, "Moodz sees it. Silent, and it sets up page 16.",
        "Moodz watching NeonBlue work, saying nothing.",
        GROUNDS, NIGHT, "close", "eye_level", "compressed_telephoto",
        "Single close head and shoulders.",
        "NeonBlue bright and heavily defocused behind, recognisable only by his cyan crown.",
        "Sharp foreground face, strongly defocused background.",
        light("Weak amber from frame right", "Amber", "Cool night ambient", "Not applicable",
              color_spill="Faint amber on his cheek from NeonBlue's direction"),
        "Quiet and dim. A held moment.",
        "None - silent panel",
        "square", "small", "subject_to_subject",
        ["character_layers/moodz close-crop", "GROUNDS plate A8 defocused"],
        ["Black fringe over one eye and blue accent correct",
         "Silent - no caption added later", "Defocus is optical, not a uniform blur"],
        blocking=[block(MZ, "Centre, close", "foreground", "Head fills half the panel",
                        "Standing still, feet out of frame",
                        "Level, off frame right, at NeonBlue", "Not visible",
                        expression_id="EXP-001-neutral")],
        approach="approved_layer_composite",
    ))
    p.append(panel(
        10, 3, "The gap between what NeonBlue says and what is happening becomes literal.",
        "NeonBlue promising, while behind him another section drops out.",
        GROUNDS, NIGHT, "medium_wide", "eye_level", "normal",
        "One figure foreground with the failure occurring behind him.",
        "NeonBlue foreground, a lit stall row behind him going dark during the panel.",
        "Figure foreground, failing row midground, dark beyond.",
        light("The failing row behind him", "Amber, dying", "Cool ambient",
              "Lengthening as the key dies", color_spill="Warm on his back edge, fading"),
        "The light is leaving him from behind while he faces front.",
        "Upper left",
        "wide", "medium", "action_to_action",
        ["GROUNDS plate A8 lights-failing", "character_layers/neonblue", CROWD],
        ["The failure is visibly happening behind him during the panel",
         "He is not looking at it", "The irony is visual, not captioned"],
        blocking=[block(NB, "Frame right, facing camera-left", "foreground",
                        "Reference figure", "Both feet, weight even",
                        "At the people he is reassuring, away from the failure",
                        "Both hands open in front of him", expression_id="EXP-005-smile")],
        dialogue=[say(NB, "It is under control.")],
    ))
    p.append(panel(
        10, 4, "Ash registers it without speaking, banking his one line for later.",
        "Ash at the frame edge, looking at NeonBlue, then away.",
        GROUNDS, NIGHT, "medium_close", "eye_level", "normal",
        "Single figure at the edge of frame with space to his side.",
        "Dark path, a sliver of the failing row behind.",
        "Shallow.",
        light("Dying amber from behind", "Weak amber", "Cool ambient", "Faint below",
              color_spill="Weak warm rim on his fringe"),
        "Dim. Waiting.", "None - silent panel",
        "rectangle", "small", "subject_to_subject",
        ["character_layers/ash", "GROUNDS plate A8 dark"],
        ["Deliberately positioned at the frame edge - he is not the subject yet",
         "Silent - his line is on page 14"],
        blocking=[block(ASH, "Far frame left, mostly at the edge", "midground",
                        "Small, deliberately marginal", "Both feet, still",
                        "At NeonBlue, then down", "Hands in hoodie pocket")],
    ))
    p.append(panel(
        10, 5, "Lift the camera so the page turn can deliver the whole picture.",
        "Looking up past the stalled ferris wheel into the dark sky.",
        GROUNDS, NIGHT, "extreme_wide", "worm_eye", "wide_distorted",
        "No cast. The ride structure against sky.",
        "The stalled ferris wheel from directly beneath, its dead lights, night sky beyond.",
        "Structure foreground and midground, sky behind. Extreme perspective convergence.",
        light("Distant festival glow from below", "Weak amber from beneath", "Night sky",
              "Not applicable",
              color_spill="Faint warm underlighting on the structure's lower edges"),
        "Dark and vertical. A held breath before the page turn.",
        "None - silent panel",
        "tall", "medium", "aspect_to_aspect",
        ["NEW GROUNDS plate A13 - ferris wheel from directly beneath"],
        ["Perspective convergence is extreme and correct", "All ride lights are dead",
         "Silent - this is a page-turn setup"],
    ))

    # ---------------- PAGE 11 - SPLASH (1) ----------------
    p.append(panel(
        11, 1,
        "The page-turn reveal. Give the reader the whole pattern at once, before any character has it.",
        "The entire festival from high above. Two vast dark arms curve in from opposite edges, closing toward a single lit point at the centre - the main stage.",
        GROUNDS, NIGHT, "extreme_wide", "birds_eye", "wide_distorted",
        "No characters, or too small to read as individuals. Scale is architectural.",
        "The whole festival site from directly above. Lit areas warm and dense. Two dark corridors of failure curve in from opposite edges toward the centre, leaving only the main stage and its crowd lit. The shape is unmistakably deliberate.",
        "Single deep plane from above. Depth read through light density and atmospheric haze, not overlap.",
        light("Self-lit from the festival below", "Warm amber where alive, nothing where dead",
              "Faint cool moonlight across everything", "Not applicable at this scale",
              cast_shadow="None readable from directly above",
              color_spill="Warm glow bleeding up from lit zones into low haze"),
        "A map made of light. The dark is the subject and it has intent.",
        "None - silent splash",
        "splash", "full_page", "aspect_to_aspect",
        ["NEW GROUNDS plate A14 - full site, birds eye, two dark arms - THE SPLASH PLATE"],
        ["SPLASH PAGE - the single most important background in the issue",
         "The two dark arms read as deliberate, not as random failure",
         "The main stage is the only substantial lit area left",
         "No character is identifiable",
         "Reads at print size without any caption explaining it",
         "Silent - no dialogue, no caption, no SFX"],
    ))

    # ---------------- PAGE 12 - LIL DEVIL (6) ----------------
    p.append(panel(
        12, 1, "Arrive at the locked gate, the last obstacle before the control node.",
        "The service gate, locked, a cyan-white worklight above it.",
        GROUNDS, NIGHT, "wide", "eye_level", "normal",
        "Three figures spread across the frame at different depths. Deliberately not a row.",
        "A service gate set into a fence line, cyan-white worklight above it, dead festival ground beyond.",
        "Fence leads the eye from foreground left to the gate at midground right.",
        light("Cyan-white gate worklight, high and frame right", "Cold cyan-white",
              "Residual warm from the distant lit section",
              "Hard-edged under the nearest figure, softer on those further",
              cast_shadow="Hard shadows thrown left along the fence",
              color_spill="Cyan on upward-facing surfaces"),
        "Cold cyan pool against warm residue. The cyan must NOT look important yet.",
        "Upper band, reading left to right",
        "wide", "medium", "scene_to_scene",
        ["GROUNDS plate A15 - service gate", "character_layers neonblue, scarline",
         LILDEVIL_LAYERS, "PROP-service-gate intact state"],
        ["Three distinct depths, no row staging",
         "Cyan spill present but reads as ordinary worklight",
         "The gate is visibly locked"],
        blocking=[
            block(LD, "Frame right at the gate, side-on", "midground",
                  "Gate frame is roughly 1.6 character heights",
                  "Both feet braced, weight forward into the gate",
                  "At the gate mechanism", "Both hands gripping the bars"),
            block(NB, "Centre, between the other two", "midground",
                  "Same ground plane, slightly nearer camera",
                  "Both feet, weight neutral, caught",
                  "Toward Lil Devil, glancing back at Scarline", "Half-raised, indecisive"),
            block(SC, "Frame left, several steps back, still", "midground",
                  "10 percent smaller - further away",
                  "Both feet, weight settled, deliberately not advancing",
                  "Level at NeonBlue, not at Lil Devil", "Arms at sides, unhurried"),
        ],
        dialogue=[say(LD, "It is a gate."), say(NB, "It is a locked gate.")],
    ))
    p.append(panel(
        12, 2, "Scarline gives him the choice rather than the instruction.",
        "Scarline, unmoving, addressing NeonBlue rather than Lil Devil.",
        GROUNDS, NIGHT, "medium_close", "eye_level", "normal",
        "Single figure, cyan-lit from one side.",
        "The fence line behind her, gate light off frame right.",
        "Shallow.",
        light("Gate worklight from frame right", "Cold cyan-white",
              "Warm residual from behind", "Not applicable",
              color_spill="Cyan on her right, warm residue on her left"),
        "Two colours on one face. She is between the warm festival and the cold system.",
        "Upper left",
        "rectangle", "small", "action_to_action",
        ["character_layers/scarline", "GROUNDS plate A15 fence"],
        ["She addresses NeonBlue, not Lil Devil - she does not police, she informs",
         "Scarlet streak reads against the cyan", "No facial scar"],
        blocking=[block(SC, "Centre, three-quarter", "midground",
                        "Head roughly a third of panel height", "Both feet, weight settled",
                        "At NeonBlue", "Arms at sides")],
        dialogue=[say(SC, "If he opens it, that is your call, not his.")],
    ))
    p.append(panel(
        12, 3, "NeonBlue hesitates - the closest he comes to being decisive so far.",
        "NeonBlue caught between them, saying the wrong careful thing.",
        GROUNDS, NIGHT, "close", "eye_level", "normal",
        "Tight single, split lighting.",
        "Dark, with the gate light hard from frame right.",
        "Shallow.",
        light("Gate worklight, hard from frame right", "Cold cyan-white", "Almost none",
              "Not applicable",
              color_spill="Hard cyan on his right half, near-black on his left"),
        "Hard split. He is half-lit by the thing he does not want to look at.",
        "Upper left",
        "rectangle", "small", "action_to_action",
        ["character_layers/neonblue close-crop", "GROUNDS plate A15"],
        ["Split is hard-edged, matching house-style cel shading",
         "Indecision, not fear", "Under-eye bags read in the dark half"],
        blocking=[block(NB, "Centre, three-quarter", "foreground",
                        "Head fills roughly half the panel", "Not visible",
                        "At the gate, avoiding Scarline", "One hand half-raised",
                        expression_id="EXP-005-worried")],
        dialogue=[say(NB, "Give me a minute to find someone with a key.")],
    ))
    p.append(panel(
        12, 4, "Lil Devil does not wait. The uncontrolled action the issue turns on.",
        "Lil Devil already moving, committed, both hands on the gate.",
        GROUNDS, NIGHT, "medium", "low_angle", "wide_distorted",
        "Single figure with real weight through the movement.",
        "The gate, the fence, the worklight above throwing him into hard relief.",
        "Figure midground, gate behind, worklight above.",
        light("Gate worklight directly above him", "Cold cyan-white", "None",
              "Hard and tight beneath both feet",
              cast_shadow="Short, hard, thrown almost straight down",
              color_spill="Cyan on every upward surface, black beneath every overhang"),
        "Maximum hard cyan. The coldest, hardest lighting so far.",
        "Upper right",
        "rectangle", "medium", "action_to_action",
        [LILDEVIL_LAYERS + " - action pose", "GROUNDS plate A15",
         "PROP-service-gate strained state"],
        ["Weight and commitment believable through the whole body",
         "Overhead source gives near-vertical shadows",
         "He is not being malicious - he is being fast"],
        blocking=[block(LD, "Centre, side-on, mid-effort", "midground",
                        "Gate frame is 1.6 character heights",
                        "One foot braced against the gate post, one planted", "At the lock",
                        "Both hands hauling on the gate")],
        dialogue=[say(LD, "You do not need a key.")],
    ))
    p.append(panel(
        12, 5, "The gate gives. The consequence is his.",
        "The gate tears open, the lock housing shearing.",
        GROUNDS, NIGHT, "medium_close", "low_angle", "normal",
        "Hands, gate and lock. Figure secondary.",
        "The lock housing shearing from the gate frame, metal deforming, the gate swinging.",
        "Shallow. Hardware detail foreground, gate beyond.",
        light("Gate worklight above", "Cold cyan-white", "None",
              "Hard shadow of the lock housing on the gate face",
              color_spill="Cyan on torn metal edges"),
        "Cold, hard, metallic.",
        "Lower left, clear of the SFX",
        "rectangle", "small", "action_to_action",
        ["PROP-service-gate forced state", LILDEVIL_LAYERS + " - hands detail"],
        ["Full house-style SFX - large, coloured, angled, may overlap the panel border",
         "Torn metal is believable", "Hands are visible and correct"],
        blocking=[block(LD, "Hands and forearms entering from frame right", "foreground",
                        "Hands near life scale against the lock housing", "Out of frame",
                        "Not visible", "Both hands on the gate as it gives")],
        sfx=["SKRRANK"],
    ))
    p.append(panel(
        12, 6, "Close on the moment before the consequence arrives.",
        "The gate hanging open, the dark service corridor beyond it, nobody moving yet.",
        GROUNDS, NIGHT, "wide", "eye_level", "normal",
        "Three small figures against a large dark opening.",
        "The forced gate hanging open. Beyond it, a dark service way. The three standing back from it.",
        "Figures foreground and midground, the dark opening as the background focal point.",
        light("Gate worklight above and behind the figures", "Cold cyan-white",
              "Nothing from inside the opening",
              "Hard beneath all three, thrown toward the opening",
              color_spill="Cyan on their backs, nothing on their faces"),
        "A hole in the world. The dark beyond the gate is total.",
        "None - silent panel",
        "wide", "medium", "moment_to_moment",
        ["GROUNDS plate A15 gate-open state", "character_layers neonblue, scarline",
         LILDEVIL_LAYERS],
        ["The opening is genuinely black - resist filling it with detail",
         "All three shadows point into the opening", "Silent - page-turn setup"],
        blocking=[
            block(LD, "Frame right, closest to the opening", "midground", "Reference figure",
                  "Both feet, weight back on his heels now", "Into the dark", "Hands lowered"),
            block(NB, "Centre", "midground", "Level with Lil Devil", "Both feet, still",
                  "Into the dark", "Arms at sides"),
            block(SC, "Frame left, furthest back", "midground", "12 percent smaller",
                  "Both feet, unmoved", "At the other two", "Arms at sides"),
        ],
    ))

    # ---------------- PAGE 13 - THE ANSWER (3) ----------------
    p.append(panel(
        13, 1, "The system responds to the interference. The discovery, and Lil Devil caused it.",
        "Inside the control node. The control box amber status light dies and cyan floods out through the panel seams.",
        NODE, NIGHT, "wide", "low_angle", "wide_distorted",
        "Strong depth separation - two foreground figures framing a midground subject, the low angle making the node loom.",
        "The control node interior. The forced gate hanging open frame left. The control box on the far wall, amber indicator dark, cyan light escaping through the panel seams and running along a floor conduit.",
        "Gate frame foreground, Lil Devil midground, control box and glowing seams background. Three planes, one floor.",
        light("From below, out of the control box seams", "Hard cyan",
              "Residual warm worklight from the corridor behind camera",
              "Hard and tight on the concrete floor",
              rim="Cyan rim along the top of Lil Devil's horns and shoulders",
              cast_shadow="Lil Devil's shadow thrown UP the wall behind him by the low source",
              color_spill="Cyan on all upward-facing surfaces, warm on the two foreground backs"),
        "Cyan takes over the panel. First time it dominates a scene rather than sitting in it.",
        "Upper right, over dark wall, clear of the SFX",
        "wide", "large", "scene_to_scene",
        ["NODE plate A - wide, low, gate open", LILDEVIL_LAYERS,
         "character_layers neonblue, ash", "PROP-service-gate forced state",
         "PROP-control-box cyan-seam state"],
        ["Lil Devil is clearly the cause - the gate is forced and he is nearest it",
         "Cyan source is BELOW and every shadow agrees",
         "Cast shadow travels UP the wall, consistent with an underlight",
         "The reaction is ambiguous, not a triumphant flare",
         "Amber status indicator visibly dead",
         "CONFLICT C-01 and C-02 - depends on owner ruling"],
        blocking=[
            block(LD, "Centre midground, turned away from camera toward the box", "midground",
                  "Control box is roughly 1.2 character heights",
                  "Both feet, weight back on his heels - recoiling slightly",
                  "At the cyan seam light",
                  "Both hands open and lowered, deliberately not touching anything"),
            block(NB, "Foreground left, entering frame", "foreground",
                  "Larger than Lil Devil, nearer camera, cropped at the knee",
                  "Mid-stride entering", "At the control box, past Lil Devil",
                  "One hand on the gate frame",
                  occlusion="The open gate frame crosses in front of him"),
            block(ASH, "Foreground left behind NeonBlue, mostly silhouette", "foreground",
                  "Slightly behind and smaller than NeonBlue", "Standing, still",
                  "At the control box", "Hands in hoodie pocket"),
        ],
        dialogue=[say(LD, "I barely touched it.")],
        sfx=["FZZK-KRRR"],
        foreground_elements=["The open gate frame, occluding NeonBlue"],
    ))
    p.append(panel(
        13, 2, "Hold on the object so the reader can study what the characters cannot.",
        "Hard insert on the control box seams, cyan pulsing through in a slow rhythm.",
        NODE, NIGHT, "extreme_close", "eye_level", "normal",
        "No cast. Object scale.",
        "The control box panel face. Cyan light escaping through the seams in a slow regular pulse. The dead amber indicator beside it.",
        "Flat and tight. One surface.",
        light("From within the box", "Hard cyan", "None", "Not applicable",
              color_spill="Cyan bleeding along every seam and screw head"),
        "Cyan on dark metal. Beautiful and wrong.",
        "None - silent panel",
        "inset", "small", "aspect_to_aspect",
        ["PROP-control-box cyan-seam state, extreme close"],
        ["The pulse rhythm is implied by the light falloff",
         "Dead amber indicator visible for contrast",
         "No readable text or numerals - nothing that dates the system"],
    ))
    p.append(panel(
        13, 3, "Close on the pulse stopping the moment they step back.",
        "The three watching. The cyan fades. The amber indicator does not come back.",
        NODE, NIGHT, "medium_wide", "eye_level", "normal",
        "Three figures at three depths in near-darkness.",
        "The control node, cyan fading out of the seams, leaving the room almost dark.",
        "Three figures midground and foreground, the box beyond, all falling to dark.",
        light("The dying cyan from the box", "Cyan, fading to nothing",
              "Weak warm from the corridor behind", "Fading as the key dies",
              color_spill="Cyan draining off every surface during the panel"),
        "Light leaving the room. The opposite of the previous panel.",
        "Upper right",
        "wide", "medium", "moment_to_moment",
        ["NODE plate A", LILDEVIL_LAYERS, "character_layers neonblue, ash",
         "PROP-control-box fading state"],
        ["The cyan is visibly fading, not already gone",
         "Amber indicator stays dead - the system did not repair itself",
         "All three are still"],
        blocking=[
            block(NB, "Centre", "midground", "Reference figure", "Both feet, weight even, still",
                  "At the box", "Arms at sides"),
            block(LD, "Frame right", "midground", "Level with NeonBlue", "Both feet, weight back",
                  "At the box", "Hands lowered"),
            block(ASH, "Frame left, furthest back", "background", "Smaller, set back",
                  "Standing still", "At NeonBlue rather than the box", "Hands in pocket"),
        ],
        dialogue=[say(NB, "It stopped when we stopped.")],
    ))

    return p
