"""Issue 001 panel data, pages 14-22. See issue001_panels.py for the contract."""

from __future__ import annotations

from scripts.production.build_panel_script import (
    ASH, CORRIDOR, GROUNDS, LATE, LD, MZ, NB, NIGHT, NODE, SC, ST, STAGE, TT,
    block, light, panel, say,
)

CROWD = "NEW crowd silhouette set"
LILDEVIL_LAYERS = "NEW Lil Devil alpha layer set - does not exist yet"
TRAPPED = "NEW three trapped festival-goer figures"


def build() -> list[dict]:
    p: list[dict] = []

    # ---------------- PAGE 14 - DENIAL AND ASH (5) ----------------
    p.append(panel(
        14, 1, "NeonBlue reaches for the ordinary explanation.",
        "NeonBlue looking at the dark box, already explaining it away.",
        NODE, NIGHT, "medium_close", "eye_level", "normal",
        "Single figure, half-lit.",
        "Dark control-node wall, faint residual cyan from frame left.",
        "Shallow. Figure against a dark near wall.",
        light("Residual cyan from frame left", "Cyan, weak", "Almost none - the unlit side falls to black",
              "Not applicable",
              color_spill="Cyan across the left half of his face, catching his under-eye shadows"),
        "Split lighting. The visual argument of the scene.",
        "Upper right, in the dark half",
        "rectangle", "small", "scene_to_scene",
        ["NODE plate B - close wall", "character_layers/neonblue close-crop"],
        ["Split lighting hard-edged, matching house-style cel shading",
         "Under-eye bags read - required canon", "Expression is denial, not fear"],
        blocking=[block(NB, "Centre, three-quarter", "foreground",
                        "Head fills roughly two fifths of panel height",
                        "Standing, feet out of frame", "At the control box, off frame left",
                        "One hand half-raised, uncommitted", expression_id="EXP-005-worried")],
        dialogue=[say(NB, "That is a surge. That is what a surge looks like.")],
    ))
    p.append(panel(
        14, 2, "Lil Devil, who caused it, is the one who will not accept the easy answer.",
        "Lil Devil, unusually serious, contradicting him.",
        NODE, NIGHT, "medium_close", "eye_level", "normal",
        "Single figure in near-darkness.",
        "The dark node interior behind him.",
        "Shallow.",
        light("Residual cyan from frame right", "Cyan, weak", "None", "Not applicable",
              color_spill="Cyan edge on his horns and one cheek"),
        "Dark. Red under cyan edge light.",
        "Upper left",
        "rectangle", "small", "action_to_action",
        [LILDEVIL_LAYERS, "NODE plate B"],
        ["He is serious, which is new for him",
         "Red outfit reads even in low cyan light", "This is his growth beginning"],
        blocking=[block(LD, "Centre, three-quarter toward NeonBlue", "midground",
                        "Head roughly a third of panel height",
                        "Both feet, weight even, still", "At NeonBlue",
                        "Arms at his sides, unusually still")],
        dialogue=[say(LD, "A surge does not wait for you to stop.")],
    ))
    p.append(panel(
        14, 3, "NeonBlue pushes back harder, which is how the reader knows he is frightened.",
        "NeonBlue turning away, dismissing it with a gesture.",
        NODE, NIGHT, "medium", "eye_level", "normal",
        "Two figures at different depths, one turning away.",
        "The dark node, the dead box behind them.",
        "Two-plane, both dim.",
        light("Weak corridor spill from behind camera", "Warm, weak", "None",
              "Faint under both", color_spill="Weak warm on their near edges"),
        "Almost no light. Two people arguing in the dark.",
        "Upper centre",
        "rectangle", "medium", "action_to_action",
        ["NODE plate A", "character_layers/neonblue", LILDEVIL_LAYERS],
        ["Turning away is the tell - his voice is up but he is retreating",
         "Both figures on the same floor plane with contact shadows"],
        blocking=[
            block(NB, "Frame left, turning away from Lil Devil", "midground",
                  "Reference figure", "Both feet, pivoting away",
                  "Away, toward the corridor exit", "One hand waving it off",
                  expression_id="EXP-005-angry"),
            block(LD, "Frame right, not moving", "midground", "Level with NeonBlue",
                  "Both feet, weight settled", "At NeonBlue's back", "Arms at sides"),
        ],
        dialogue=[say(NB, "Then it is a fault with a rhythm. It is still a fault.")],
    ))
    p.append(panel(
        14, 4, "Ash's one line in the issue, at the exact point of denial.",
        "Ash, half-lidded, not looking at NeonBlue, saying five words.",
        NODE, NIGHT, "close", "eye_level", "compressed_telephoto",
        "Over-shoulder-style two-shot with real depth separation between the heads.",
        "Dark control-node interior, faint cyan behind them.",
        "Two heads at clearly different distances, background falling to dark.",
        light("Faint cyan from behind and left", "Cyan", "Very low warm",
              "Not applicable", rim="Cyan rim on both silhouettes",
              color_spill="Cyan edge light along Ash's silver-white fringe"),
        "Dark and close. The quietest panel on the page carries its weight.",
        "Upper centre, between the two heads",
        "rectangle", "medium", "action_to_action",
        ["NODE plate B", "character_layers ash, neonblue close-crop"],
        ["Ash's silver-white fringe and half-lidded eyes read",
         "Ash is visibly NOT looking at NeonBlue",
         "Line is exactly the season bible wording",
         "This is Ash's ONLY line in the issue"],
        blocking=[
            block(ASH, "Foreground right, turned away, three-quarter rear", "foreground",
                  "Larger, nearer, partly cropped by the frame edge",
                  "Standing, feet out of frame",
                  "Straight ahead at the control box, deliberately not at NeonBlue",
                  "Not visible"),
            block(NB, "Midground left, facing toward Ash", "midground",
                  "Smaller, further, fully visible head", "Standing, feet out of frame",
                  "At Ash", "Not visible", expression_id="EXP-005-confused"),
        ],
        dialogue=[say(ASH, "Hope can read warnings.")],
    ))
    p.append(panel(
        14, 5, "Close the page on NeonBlue absorbing it without answering.",
        "NeonBlue alone in frame, saying nothing, the fight gone out of his shoulders.",
        NODE, NIGHT, "medium", "high_angle", "normal",
        "Single figure seen slightly from above, which makes him smaller.",
        "The node floor, conduit lines running away, the dead box at the frame edge.",
        "Figure midground on a visible floor plane, conduit receding.",
        light("Weak corridor spill from behind camera", "Warm, weak", "None",
              "Present under both feet on the concrete",
              color_spill="Weak warm on his shoulders and the top of his head"),
        "Dim and diminishing. The high angle does the work.",
        "None - silent panel",
        "rectangle", "medium", "subject_to_subject",
        ["NODE plate A floor", "character_layers/neonblue"],
        ["High angle makes him smaller - deliberate",
         "Silent - he does not answer Ash", "Contact shadows on visible concrete"],
        blocking=[block(NB, "Centre, seen from above, shoulders dropped", "midground",
                        "Reference figure, diminished by the angle",
                        "Both feet flat, weight settled back", "Down at the floor",
                        "Arms hanging", expression_id="EXP-005-defeated")],
    ))

    # ---------------- PAGE 15 - THE MARKER (3) ----------------
    p.append(panel(
        15, 1, "Move into the corridor. Change the world of the issue.",
        "The service corridor running away into the dark, one distant practical.",
        CORRIDOR, NIGHT, "wide", "eye_level", "wide_distorted",
        "One small figure entering a large empty space.",
        "The service corridor. Pipework along one wall, floor grating, one distant practical far down.",
        "Deep one-point perspective. The vanishing point is the subject.",
        light("Distant practical far down the corridor", "Cool sodium-white",
              "Faint warm from behind", "Long soft shadow thrown back toward camera",
              color_spill="Cool light on his front edge, warm on his back"),
        "Almost monochrome. A different world from the festival.",
        "None - silent panel",
        "tall", "medium", "scene_to_scene",
        ["CORRIDOR plate A - deep one-point", "character_layers/neonblue"],
        ["Perspective lines converge correctly on one vanishing point",
         "At least 70 percent of the frame is empty corridor",
         "Back-view silhouette identifiable as NeonBlue by the spike crown"],
        blocking=[block(NB, "Small, low, frame left, facing away from camera", "midground",
                        "Roughly one sixth of panel height - dwarfed by the corridor",
                        "Both feet flat, walking slowly", "Away from camera, down the corridor",
                        "One hand trailing along the wall")],
    ))
    p.append(panel(
        15, 2, "The midpoint. The danger becomes personal through an object, not a flashback.",
        "NeonBlue's hand stops on an old relay marker. A worn frequency stamp glows faintly cyan.",
        CORRIDOR, NIGHT, "extreme_close", "eye_level", "normal",
        "Object scale, not figure scale. The marker is the subject.",
        "Old service corridor wall. A small worn metal relay marker bolted to conduit, its stamped frequency faintly luminous cyan. One practical far down the corridor behind.",
        "Very shallow foreground on the marker, corridor falling away to a distant point of light behind.",
        light("The marker's own faint cyan, plus a distant corridor practical",
              "Faint cyan close, warm sodium far", "Almost none",
              "His hand casts a soft shadow on the wall plate",
              color_spill="Cyan on his palm and fingers, warm rim on his hair from the far light"),
        "Nearly black with two small light sources. The most intimate panel in the issue.",
        "Lower left, small whisper balloon near his face",
        "tall", "large", "action_to_action",
        ["CORRIDOR plate B - close wall detail", "PROP-cyan-relay-marker close-detail state",
         "character_layers/neonblue hand and partial face"],
        ["The marker reads as old without being dated - no numerals implying an age",
         "The stamped frequency is visible but not readable as specific text",
         "His hand has stopped - no motion implied",
         "Patch is named exactly ONCE in the whole issue"],
        blocking=[block(NB, "Hand upper-centre on the marker, face entering only at the bottom edge",
                        "foreground", "Hand at near-life scale against the marker plate",
                        "Standing, feet out of frame", "At the marker, very close to it",
                        "One flat hand resting on the marker plate, stopped")],
        dialogue=[say(NB, "...Patch used this one.", "whisper")],
    ))
    p.append(panel(
        15, 3, "Hold on his face for one panel. No dialogue, no explanation.",
        "NeonBlue's face in the near-dark, the cyan stamp light on one side.",
        CORRIDOR, NIGHT, "close", "eye_level", "compressed_telephoto",
        "Tight single, mostly dark.",
        "Near-black corridor wall, faint cyan from the marker off frame.",
        "Shallow.",
        light("The marker's faint cyan, from frame left and low", "Faint cyan", "Almost none",
              "Not applicable",
              color_spill="Faint cyan under-light on one cheek and the underside of his brow"),
        "Almost nothing. One small cold light on a face.",
        "None - silent panel",
        "square", "medium", "moment_to_moment",
        ["character_layers/neonblue close-crop", "CORRIDOR plate B"],
        ["Silent - no caption explaining what he feels",
         "The expression is not grief - it is recognition",
         "Under-eye bags heavily present in this light"],
        blocking=[block(NB, "Centre, close, lit faintly from below-left", "foreground",
                        "Head fills the panel", "Not visible",
                        "Down and away, unfocused", "Not visible",
                        expression_id="EXP-005-sad")],
        approach="approved_layer_composite",
    ))

    # ---------------- PAGE 16 - PERMISSION (4) ----------------
    p.append(panel(
        16, 1, "Moodz arrives without being called.",
        "Moodz entering the corridor behind him, stopping at a distance.",
        CORRIDOR, NIGHT, "wide", "eye_level", "normal",
        "Two figures at clearly different depths in a corridor.",
        "The corridor, NeonBlue at the marker, Moodz entering from the far end.",
        "NeonBlue midground, Moodz background, corridor connecting them.",
        light("Overhead red practical between them", "Deep red-orange",
              "Faint cyan bounce from the corridor's far end",
              "Hard contact shadows under both on the grating",
              color_spill="Red on their upper surfaces, cyan on their far sides"),
        "Warm red and cold cyan meeting in a dark corridor.",
        "None - silent panel",
        "wide", "medium", "scene_to_scene",
        ["CORRIDOR plate A", "character_layers neonblue, moodz"],
        ["The depth gap between them is the content - do not close it",
         "Contact shadows follow the grating pattern, not generic ellipses",
         "Moodz stops rather than approaching"],
        blocking=[
            block(NB, "Frame left, at the wall, side-on", "midground",
                  "Corridor door frame is roughly 1.5 character heights",
                  "Both feet flat on the grating, weight settled back", "At the wall",
                  "One hand still against the wall"),
            block(MZ, "Frame right, far down the corridor, stopped", "background",
                  "Roughly 60 percent of NeonBlue's apparent height",
                  "Both feet flat, weight even, stopped", "At NeonBlue", "Hands in pockets"),
        ],
    ))
    p.append(panel(
        16, 2, "Moodz removes the obligation rather than issuing an instruction.",
        "Moodz closer now, still not touching him.",
        CORRIDOR, NIGHT, "medium", "eye_level", "normal",
        "Two figures on one hard floor plane at measurably different depths. The controlled-test panel.",
        "Service corridor running away from camera. Pipework along one wall, a red practical overhead midway, floor grating underfoot.",
        "NeonBlue nearer, Moodz further, corridor continuing past both to darkness. Depth read through scale, light falloff and floor perspective.",
        light("Overhead red practical, between and slightly behind them", "Deep red-orange",
              "Faint cyan bounce from the corridor's far end",
              "Hard contact shadow under both, on grating - shadow shape must follow the grating pattern",
              rim="Red rim on the inner shoulder of each figure",
              cast_shadow="Both throw short shadows toward camera from the overhead source",
              color_spill="Red on upward and inward-facing surfaces, cool cyan on the far side of each figure"),
        "Warm red and cold cyan meeting. Two people, two colours, one floor.",
        "Upper centre, two stacked balloons reading top to bottom, clear of both faces",
        "rectangle", "large", "action_to_action",
        ["CORRIDOR plate A - deep one-point", "character_layers neonblue, moodz"],
        ["CONTROLLED TEST PANEL - method gate before any bulk generation",
         "Both characters recognisable against approved reference",
         "Feet meet the grating with correct perspective",
         "Contact shadow follows the grating pattern, not a generic ellipse",
         "Key light direction matches the overhead practical on both figures",
         "No matte halo at any character edge",
         "Relative scale consistent with the door frame reference",
         "Moodz is visibly not reaching toward NeonBlue",
         "Reads as house style beside an Edition Two panel"],
        blocking=[
            block(NB, "Frame left, side-on to camera, back near the wall", "midground",
                  "Measured against the corridor door frame, roughly 1.5 character heights",
                  "Both feet flat on the corridor floor, weight settled back", "At Moodz",
                  "One hand still against the wall", expression_id="EXP-005-sad"),
            block(MZ, "Frame right, a clear step further from camera, facing NeonBlue", "midground",
                  "8 percent smaller than NeonBlue - measurably further down the corridor",
                  "Both feet flat, weight even, standing still", "Level at NeonBlue",
                  "Hands at his sides - deliberately not reaching out",
                  expression_id="EXP-001-neutral"),
        ],
        dialogue=[say(MZ, "Your smile's wider than usual."),
                  say(MZ, "You don't have to sell it to us.")],
    ))
    p.append(panel(
        16, 3, "NeonBlue does not answer. He also does not argue.",
        "NeonBlue's shoulders dropping. A small, real change.",
        CORRIDOR, NIGHT, "medium_close", "eye_level", "normal",
        "Single figure, red-lit.",
        "Corridor wall behind, red practical overhead.",
        "Shallow.",
        light("Overhead red practical", "Deep red-orange", "Faint cyan from behind",
              "Not applicable", rim="Red top rim on his hair and shoulders",
              color_spill="Red on upward surfaces, cyan on the underside"),
        "Warm red on a tired face.",
        "None - silent panel",
        "rectangle", "small", "moment_to_moment",
        ["CORRIDOR plate A", "character_layers/neonblue"],
        ["The change is small and physical - shoulders, not expression",
         "Silent", "He does not perform for Moodz"],
        blocking=[block(NB, "Centre, three-quarter, shoulders dropping", "midground",
                        "Head roughly a third of panel height",
                        "Both feet flat, weight settling", "Down, then at Moodz",
                        "Hand coming off the wall", expression_id="EXP-005-sleepy")],
    ))
    p.append(panel(
        16, 4, "Close the page with Moodz saying the smallest useful thing and leaving.",
        "Moodz turning to go, having said what he came to say.",
        CORRIDOR, NIGHT, "medium_wide", "eye_level", "normal",
        "Two figures, one leaving, on one floor plane.",
        "The corridor, Moodz walking back toward the far end.",
        "NeonBlue midground still, Moodz moving into background.",
        light("Overhead red practical", "Deep red-orange", "Cyan from the far end",
              "Both figures have grating-patterned contact shadows",
              color_spill="Red above, cyan ahead of Moodz as he walks toward it"),
        "He walks toward the cold end. It is not ominous, just the way out.",
        "Upper left",
        "wide", "medium", "action_to_action",
        ["CORRIDOR plate A", "character_layers neonblue, moodz"],
        ["Moodz does not wait for a response - that is the point",
         "Both contact shadows follow the grating"],
        blocking=[
            block(MZ, "Centre, walking away from camera", "midground", "Reference figure",
                  "Both feet, walking, unhurried", "Ahead down the corridor",
                  "Hands in pockets"),
            block(NB, "Frame left, still at the wall", "midground", "Level with Moodz",
                  "Both feet flat, still", "At Moodz's back", "Arms at sides"),
        ],
        dialogue=[say(MZ, "We are on the service side if you want us.")],
    ))

    # ---------------- PAGE 17 - THE BREATH (2) ----------------
    p.append(panel(
        17, 1, "Let the midpoint land. Deliberate negative space, borrowed from Edition Three.",
        "NeonBlue alone in the corridor, facing away, the corridor running off into dark.",
        CORRIDOR, NIGHT, "extreme_wide", "eye_level", "wide_distorted",
        "One small figure in a large empty space. The emptiness is the content.",
        "The service corridor stretching away, mostly empty. Pipework, grating, one distant light. Nothing happening.",
        "Deep one-point perspective. The vanishing point is the emotional subject.",
        light("Distant practical far down the corridor, ahead of him", "Cool sodium-white",
              "Faint red spill from behind", "Long soft shadow thrown back toward camera",
              color_spill="Cool light on his front edge, warm red on his back"),
        "Almost monochrome. Quiet.",
        "None - silent panel",
        "wide", "large", "moment_to_moment",
        ["CORRIDOR plate A", "character_layers/neonblue back view"],
        ["Silent, and stays silent - no caption added later",
         "At least 70 percent of the frame is empty corridor",
         "Back-view silhouette identifiable by the spike crown",
         "Perspective converges on one vanishing point"],
        blocking=[block(NB, "Small, low, frame left, facing away from camera", "midground",
                        "Roughly one sixth of panel height - dwarfed by the corridor",
                        "Both feet flat, weight settled, still", "Away, down the corridor",
                        "One hand still resting on the wall")],
    ))
    p.append(panel(
        17, 2, "One panel of pure held time before the crisis page.",
        "Insert on the relay marker alone, his hand gone. The cyan stamp still faintly lit.",
        CORRIDOR, NIGHT, "extreme_close", "eye_level", "normal",
        "No cast. Object only.",
        "The relay marker on the conduit. Nobody touching it. The stamped frequency still faintly cyan.",
        "Flat and tight. One object.",
        light("The marker's own faint cyan", "Faint cyan", "Almost none", "Not applicable",
              color_spill="Faint cyan on the surrounding conduit"),
        "One small cold light and nothing else.",
        "None - silent panel",
        "inset", "medium", "aspect_to_aspect",
        ["PROP-cyan-relay-marker close-detail state"],
        ["Silent", "Nobody is present", "The marker is unchanged from panel 15-2",
         "No numerals or text that would date the system"],
    ))

    # ---------------- PAGE 18 - THE COUNTDOWN AND THE THREE (7, DENSE) ----
    p.append(panel(
        18, 1, "The countdown begins. The pull toward the visible thing.",
        "The countdown board on the main stage lighting up, numbers starting.",
        STAGE, NIGHT, "insert", "low_angle", "compressed_telephoto",
        "No cast. The board fills the frame.",
        "The countdown board, numbers illuminated and starting to fall.",
        "Flat and tight.",
        light("The board itself", "Hard white", "None", "Not applicable",
              color_spill="White bleeding into the haze around the board"),
        "The brightest thing left in the festival.",
        "Upper left, SFX only",
        "wide", "small", "scene_to_scene",
        ["NEW STAGE plate C - countdown board insert"],
        ["Numbers legible", "Brightest element on the page"],
        sfx=["TEN -"],
    ))
    p.append(panel(
        18, 2, "The whole festival turns one way.",
        "The crowd massed at the stage, seen from within and below, every face pointed the same way.",
        STAGE, NIGHT, "extreme_wide", "low_angle", "wide_distorted",
        "No cast member identifiable. Crowd scale gives the stage its size.",
        "The stage from within the crowd and below. Countdown board lit above. Crowd heads and raised arms filling the lower frame in silhouette.",
        "Dense silhouette foreground, crowd mass midground, lit stage background.",
        light("From the stage, ahead and above", "Hard white and magenta stage wash",
              "None - everything not lit by the stage is black", "Not applicable",
              color_spill="Stage light rimming the tops of hundreds of heads"),
        "Blinding stage light against total crowd silhouette. Maximum contrast in the issue.",
        "Upper left, SFX only",
        "wide", "medium", "action_to_action",
        ["NEW STAGE plate B - low angle from crowd", CROWD + " - dense"],
        ["No Emo Monkey identifiable in the crowd",
         "Crowd silhouettes read as individual people, not a texture",
         "The pull of this panel is felt - it should look like the right place to be"],
        sfx=["NINE - EIGHT -"],
    ))
    p.append(panel(
        18, 3, "Static hears something the countdown is drowning out.",
        "Static turning away from the stage, toward the dark.",
        STAGE, NIGHT, "medium", "eye_level", "normal",
        "One figure turning against a crowd all facing the other way.",
        "The back of the crowd, stage light from behind, dark service side ahead.",
        "Crowd behind him lit, Static midground turning, dark ahead.",
        light("Stage from behind him", "Hard white", "Nothing ahead",
              "Present, thrown forward into the dark",
              rim="Hard white rim on his back and shoulders",
              color_spill="White on his back, nothing on his face"),
        "Backlit. His face is the only dark thing pointed at the dark.",
        "Upper right",
        "rectangle", "medium", "subject_to_subject",
        ["NEW STAGE plate B", "character_layers/static", CROWD],
        ["He is the only figure facing away from the stage",
         "Face unlit and back rim-lit - strong silhouette read"],
        blocking=[block(ST, "Centre, turning away from the stage toward camera-left", "midground",
                        "Reference figure", "Both feet, pivoting", "Off into the dark service side",
                        "One hand near his ear", expression_id="EXP-003-worried")],
        dialogue=[say(ST, "There is something under it.")],
    ))
    p.append(panel(
        18, 4, "Static and Scarline move against the crowd.",
        "The two pushing back through the crowd toward the service corridor.",
        GROUNDS, NIGHT, "medium_wide", "eye_level", "normal",
        "Two figures moving against a dense crowd current.",
        "The crowd edge, bodies pressing the other way, the dark service side ahead.",
        "Crowd foreground and midground, the two pushing through, dark ahead.",
        light("Stage light from behind the crowd", "Hard white", "None ahead",
              "Present under both, crowded by other shadows",
              color_spill="White rim on everyone, faces dark"),
        "Backlit and crowded. Hard going.",
        "Upper left",
        "wide", "medium", "action_to_action",
        ["GROUNDS plate A9 crowd edge", "character_layers static, scarline", CROWD],
        ["Both are physically pushing against the flow",
         "Crowd occlusion is genuine - people cross in front of them"],
        blocking=[
            block(ST, "Frame left, leading", "midground", "Reference figure",
                  "Both feet, shouldering forward", "Ahead into the dark",
                  "One arm raised to make a path",
                  occlusion="Crowd silhouettes cross in front of him"),
            block(SC, "Frame right, following close", "midground", "6 percent smaller",
                  "Both feet, steady", "Ahead", "One hand on Static's shoulder to stay together"),
        ],
    ))
    p.append(panel(
        18, 5, "The corridor. Everything the countdown is not.",
        "The service corridor, dark, one red practical, silent.",
        CORRIDOR, NIGHT, "wide", "eye_level", "normal",
        "No cast. Empty corridor.",
        "The service corridor, empty, one red practical, the countdown audible but far.",
        "Deep, empty.",
        light("One red practical overhead", "Deep red", "None",
              "Not applicable - nobody present",
              color_spill="Red on the pipework directly beneath the practical"),
        "Silent, red, and empty. The opposite of the previous panels.",
        "None - silent panel",
        "wide", "small", "scene_to_scene",
        ["CORRIDOR plate A"],
        ["Empty of people", "The contrast with the crowd panels is the point"],
    ))
    p.append(panel(
        18, 6, "The stakes get faces. Established here so page 21 has someone in it.",
        "Three young festival-goers behind a jammed emergency shutter. Small, distinct, frightened, not hurt.",
        CORRIDOR, NIGHT, "wide", "low_angle", "normal",
        "Two cast figures in the foreground and three smaller extras beyond the grating at a clearly greater depth.",
        "A jammed emergency shutter, half lowered, heavy grating. Beyond it a dark holding space with three young festival-goers - individually distinct in silhouette and readable in the face. One red corridor practical is the only strong light.",
        "Cast foreground, grating as a hard midground plane, trapped figures beyond. Occlusion by the grating is essential.",
        light("Single red practical, corridor side, frame right", "Deep red",
              "Very faint light from beyond the shutter",
              "Hard under Static and Scarline on the corridor floor",
              cast_shadow="Grating shadow striping across the corridor floor",
              color_spill="Red on the cast, the trapped three lit only by weak spill and reading cooler"),
        "Near-black with one red source. The darkest panel in the issue.",
        "Upper left, clear of the grating and all faces",
        "wide", "large", "action_to_action",
        ["NEW CORRIDOR plate C - shutter, low angle", "character_layers static, scarline", TRAPPED],
        ["All three trapped figures individually distinct in silhouette",
         "Their faces are readable - they are people, not shapes",
         "NONE of them is injured",
         "Grating occlusion is genuine, passing in front of them",
         "Grating shadow stripes the floor consistently with the red source"],
        blocking=[
            block(ST, "Foreground left, hand flat against the shutter, partly silhouetted",
                  "foreground", "Largest figure, measured against the shutter frame",
                  "Both feet, weight forward into the shutter", "Through the grating at the three",
                  "One flat palm pressed on the metal", expression_id="EXP-003-shocked"),
            block(SC, "Foreground right, a step back, watching", "foreground",
                  "Slightly smaller than Static, further from the shutter",
                  "Both feet, weight settled", "Through the grating", "Arms at sides"),
        ],
        dialogue=[say(ST, "Three. Behind the shutter.")],
        foreground_elements=["The shutter and its grating, crossing in front of the trapped figures"],
    ))
    p.append(panel(
        18, 7, "Close the dense page on the two things happening at once.",
        "Split composition - the countdown glow at one edge of frame, the red shutter at the other, and the dark between them.",
        CORRIDOR, NIGHT, "extreme_wide", "eye_level", "wide_distorted",
        "No cast. Two light sources at opposite edges and darkness between.",
        "The junction where the corridor meets the grounds. Countdown white spilling in from one edge, red shutter light at the other, a wide band of nothing between them.",
        "Two lit edges, one dark centre. Depth from the falloff on both sides.",
        light("Two competing sources at opposite frame edges",
              "Cool white at one edge, deep red at the other",
              "Neither reaches the centre", "Not applicable - no figures",
              color_spill="Each colour falls off toward the centre and dies"),
        "Two colours, one dark gap. The choice, stated as a composition before anyone makes it.",
        "None - silent panel",
        "wide", "medium", "aspect_to_aspect",
        ["NEW CORRIDOR plate D - junction, dual light, empty"],
        ["Both light sources visible at opposite edges",
         "The dark band between them is genuinely dark",
         "Silent - this is the page-turn into the decision",
         "No character present - the next page puts one here"],
    ))

    # ---------------- PAGE 19 - THE DECISION (2) ----------------
    p.append(panel(
        19, 1, "The decision. The emotional centre of the issue.",
        "NeonBlue at the junction, lit from one side by the countdown and the other by the red corridor, with nobody telling him anything.",
        CORRIDOR, NIGHT, "medium", "low_angle", "normal",
        "One figure at decision scale with a small, deliberately distant second figure. Scarline's distance is the meaning.",
        "The junction where the corridor meets the open grounds. Countdown light spilling in from the grounds side, red corridor practical from the other.",
        "NeonBlue midground on the junction floor, Scarline background, two competing light sources beyond each.",
        light("Two competing keys - cool white countdown from frame left, deep red corridor from frame right",
              "Cool white left, deep red right",
              "Neither source fills the other's shadow - the centre of his face is the darkest part",
              "TWO contact shadows under him, one per source, falling in opposite directions",
              rim="Cool rim on his left silhouette, red rim on his right",
              cast_shadow="Two overlapping cast shadows, one cool-edged and one warm-edged",
              color_spill="Cool white on his left, red on his right, meeting down the centre line of his face"),
        "Two colours, two directions, one figure. The whole issue in one lighting setup.",
        "Upper right, near Scarline, tail running back to her",
        "rectangle", "large", "scene_to_scene",
        ["NEW CORRIDOR plate D - junction, dual light", "character_layers neonblue, scarline"],
        ["Two distinct light sources produce TWO distinct contact shadows",
         "The cool and red spills meet down the centre of his face",
         "He is off-centre toward the corridor side BEFORE he has moved",
         "Scarline is visibly not intervening and not reaching",
         "Her line validates without instructing",
         "The emotional centre - the strongest image on the page"],
        blocking=[
            block(NB, "Centre but pushed toward the corridor side of frame before he has moved",
                  "midground", "Head roughly a third of panel height, measured against the junction door frame",
                  "Both feet flat, weight subtly shifted onto the corridor-side foot",
                  "Not at either light - middle distance, deciding",
                  "Hands loose at his sides, open", expression_id="EXP-005-determined"),
            block(SC, "Background right at the frame edge, small, still", "background",
                  "Roughly half NeonBlue's apparent height - clearly set back",
                  "Both feet, weight settled, deliberately not advancing", "At NeonBlue",
                  "Arms at sides, not reaching"),
        ],
        dialogue=[say(SC, "Both of those are real choices.")],
    ))
    p.append(panel(
        19, 2, "He moves. One panel, no dialogue, no caption.",
        "NeonBlue walking into the red, away from the white, seen from behind.",
        CORRIDOR, NIGHT, "medium_wide", "eye_level", "normal",
        "One figure moving away, with the abandoned light behind him.",
        "The corridor mouth, red ahead, the countdown white falling away behind.",
        "Figure midground moving away, red ahead, white behind.",
        light("Red practical ahead, countdown white behind", "Deep red ahead, cool white behind",
              "Neither fills", "Present, thrown back toward the white",
              rim="Red rim on his front edge, white rim on his back",
              color_spill="Red ahead, white behind, meeting on him"),
        "He walks into the red. The warm public light is behind him now.",
        "None - silent panel",
        "wide", "large", "action_to_action",
        ["NEW CORRIDOR plate D - junction, dual light", "character_layers/neonblue back view"],
        ["Silent - the decision is not narrated",
         "He is moving INTO the red and AWAY from the white",
         "Back-view silhouette identifiable by the spike crown",
         "Both rim colours present on the same figure"],
        blocking=[block(NB, "Centre, walking away from camera into the red", "midground",
                        "Mid-scale, diminishing", "Both feet, committed stride",
                        "Ahead into the corridor", "Arms swinging, moving with purpose")],
    ))

    # ---------------- PAGE 20 - THE PLAN (6) ----------------
    p.append(panel(
        20, 1, "Hope that admits risk. Leadership without a guarantee.",
        "NeonBlue with the team around him, not smiling, pointing at the shutter hinge.",
        CORRIDOR, NIGHT, "medium_wide", "low_angle", "normal",
        "Five figures at five different depths, three different heights, two different postures. Explicitly the anti-lineup panel.",
        "The corridor at the shutter. Torches propped on the floor throwing light upward. Tools and a route diagram scattered.",
        "Crouched foreground figure, standing midground pair, two background figures, shutter beyond. Four depth steps.",
        light("Torches on the floor, throwing light upward", "Warm working white",
              "Weak red from the corridor practical", "Hard and tight - the sources are close and low",
              rim="Warm underlight rim on every chin and forearm",
              cast_shadow="All five shadows thrown UP the walls and ceiling, radiating from the floor torches",
              color_spill="Warm on undersides, red residue on backs"),
        "Warmth returning, but working warmth - torchlight, not festival light.",
        "Upper left, two stacked balloons, clear of all five faces",
        "wide", "large", "scene_to_scene",
        ["NEW CORRIDOR plate C variant - torch-lit",
         "character_layers neonblue, twotone, static, ash", LILDEVIL_LAYERS],
        ["Five characters at five distinct depths - measure and confirm",
         "No two characters at the same apparent scale",
         "At least one crouched and one turned away",
         "All shadows radiate UPWARD from floor-level sources",
         "NeonBlue is NOT smiling",
         "Blocking reads as a working team, not a group portrait"],
        blocking=[
            block(NB, "Centre-left, standing, arm extended toward the hinge", "midground",
                  "Reference figure for the panel, measured against the shutter",
                  "Both feet planted, weight forward", "At the team, not at the hinge",
                  "One arm fully extended, index finger marking the hinge",
                  expression_id="EXP-005-determined"),
            block(LD, "Right of NeonBlue, closest to the shutter, already leaning in", "midground",
                  "Same ground plane, slightly nearer camera", "Both feet braced, weight forward",
                  "At the hinge", "Flexing both hands"),
            block(TT, "Foreground left, crouched over a route diagram, back partly to camera",
                  "foreground", "Largest in frame because he is nearest and crouched forward",
                  "Crouched - one knee down, one foot flat", "Down at the diagram",
                  "Both hands on the diagram"),
            block(ST, "Background right, half-turned away, hand near the wall", "background",
                  "Smallest - clearly furthest back", "Both feet, weight shifting",
                  "Away, down the corridor, listening to something else",
                  "One hand flat on the wall"),
            block(ASH, "Background left, still, mostly silhouette", "background",
                  "Small, set back", "Standing still", "At NeonBlue", "Hands in hoodie pocket"),
        ],
        dialogue=[say(NB, "I can't promise the grid holds."),
                  say(NB, "Here's how we get them out anyway.")],
    ))
    p.append(panel(
        20, 2, "TwoTone contributes at the climax.",
        "Insert on TwoTone's hand tracing a route under a marked conduit.",
        CORRIDOR, NIGHT, "insert", "high_angle", "normal",
        "Hand and diagram only. No face.",
        "A hand-marked route diagram on paper, torch-lit, a conduit run marked in heavy line.",
        "Shallow. This is detail, not space.",
        light("Torchlight from below-left", "Warm working white", "Faint red",
              "Hand shadow falling across the diagram", color_spill="Warm underlight on his hand"),
        "Warm and tight.",
        "Upper right",
        "inset", "small", "subject_to_subject",
        ["NEW route diagram prop", "character_layers/twotone hand detail"],
        ["No full figure", "The route diagram is legible as a diagram without readable text",
         "Hand shadow lands correctly on the paper"],
        blocking=[block(TT, "Hand entering from frame bottom", "foreground",
                        "Hand near life scale on the diagram", "Crouched, out of frame",
                        "Not visible", "One finger tracing a route under a marked conduit")],
        dialogue=[say(TT, "Left conduit's still live. Go under it.")],
    ))
    p.append(panel(
        20, 3, "Static contributes at the climax.",
        "Tight on Static's face, counting.",
        CORRIDOR, NIGHT, "close", "eye_level", "normal",
        "Tight single, no full figure.",
        "Dark corridor wall behind his head.",
        "Shallow.",
        light("Torchlight from below", "Warm working white", "Faint red", "Not applicable",
              color_spill="Warm underlight on his jaw and the underside of his brow"),
        "Warm underlight on a concentrating face.",
        "Upper left",
        "inset", "small", "subject_to_subject",
        ["character_layers/static close-crop"],
        ["No full figure", "He reads as counting, not panicking",
         "Underlight consistent with the floor torches"],
        blocking=[block(ST, "Centre, tight", "foreground", "Face fills the panel",
                        "Not visible", "Unfocused, counting", "Not visible",
                        expression_id="EXP-003-determined")],
        dialogue=[say(ST, "Surge every nine seconds. Go on eight.")],
        approach="approved_layer_composite",
    ))
    p.append(panel(
        20, 4, "NeonBlue marks the exact point, which is what makes the force useful.",
        "NeonBlue's hand chalking a mark on the shutter hinge.",
        CORRIDOR, NIGHT, "extreme_close", "eye_level", "normal",
        "Hand and hinge. Object scale.",
        "The shutter hinge, rusted, a chalk mark being drawn on it.",
        "Shallow. Hardware and hand.",
        light("Torchlight from below", "Warm working white", "Faint red",
              "Hard hand shadow on the hinge plate",
              color_spill="Warm on the metal, chalk reading bright"),
        "Warm, tight, specific.",
        "None - silent panel",
        "inset", "small", "action_to_action",
        ["PROP-service-gate hinge detail", "character_layers/neonblue hand"],
        ["The chalk mark is clearly visible - it must be recognisable again in panel 21-1",
         "Hand anatomy correct", "Hard shadow from a low source"],
        blocking=[block(NB, "Hand entering from frame left", "foreground",
                        "Hand near life scale against the hinge",
                        "Standing, out of frame", "At the hinge",
                        "One hand drawing a chalk mark")],
    ))
    p.append(panel(
        20, 5, "Ash is present and useful without speaking again.",
        "Ash holding a torch steady so NeonBlue can see the hinge.",
        CORRIDOR, NIGHT, "medium", "eye_level", "normal",
        "One figure with a light source in frame.",
        "The corridor, Ash's torch as a visible practical, the shutter behind.",
        "Ash midground with the torch, shutter background.",
        light("The torch Ash is holding, in frame", "Warm working white", "Weak red",
              "Present under him", rim="Warm rim on his forearm and the torch body",
              color_spill="Warm cone from the torch across the frame"),
        "One person holding a light steady. Unglamorous and necessary.",
        "None - silent panel",
        "rectangle", "small", "subject_to_subject",
        ["CORRIDOR plate C torch-lit", "character_layers/ash"],
        ["He does not speak again - one line per issue",
         "The torch beam direction matches the lighting in the neighbouring panels",
         "Silent"],
        blocking=[block(ASH, "Frame right, arm extended holding a torch", "midground",
                        "Reference figure", "Both feet, weight even, steady",
                        "At what the torch is lighting", "One hand holding a torch steady")],
    ))
    p.append(panel(
        20, 6, "Close the page on the team ready and the countdown still running.",
        "The five in position, the shutter ahead, the countdown audible off-panel.",
        CORRIDOR, NIGHT, "wide", "eye_level", "normal",
        "Five figures spread across a corridor at five depths, all facing one way.",
        "The corridor at the shutter, torches on the floor, everyone in position.",
        "Five depth steps toward the shutter.",
        light("Floor torches", "Warm working white", "Weak red",
              "Hard, tight, upward-throwing on all five",
              cast_shadow="Five shadows up the walls, radiating from the floor",
              color_spill="Warm undersides throughout"),
        "Warm working light. A team about to do something difficult.",
        "Upper right, SFX only",
        "wide", "medium", "action_to_action",
        ["CORRIDOR plate C torch-lit", "character_layers neonblue, twotone, static, ash",
         LILDEVIL_LAYERS],
        ["Five distinct depths again, different from panel 20-1",
         "All five oriented toward the shutter", "Nobody is centred"],
        blocking=[
            block(LD, "Frame right, nearest the shutter", "midground", "Reference figure",
                  "Both feet braced", "At the chalk mark", "Both hands ready"),
            block(NB, "Centre-right, behind Lil Devil", "midground", "8 percent smaller",
                  "Both feet, weight forward", "At the chalk mark", "One hand raised, holding"),
            block(TT, "Centre-left", "midground", "12 percent smaller", "Both feet",
                  "At the conduit above", "One hand pointing up at the live conduit"),
            block(ST, "Frame left, back to the wall", "background", "Smaller",
                  "Both feet, back against the wall", "Unfocused, counting", "One hand raised, counting"),
            block(ASH, "Far frame left, torch out", "background", "Smallest",
                  "Both feet, steady", "At the hinge", "Torch held out"),
        ],
        sfx=["THREE -"],
    ))

    # ---------------- PAGE 21 - THE WORK (5) ----------------
    p.append(panel(
        21, 1, "Directed force works. Lil Devil's growth is visible, not stated.",
        "Lil Devil hits the hinge exactly where NeonBlue chalked it. Sparks. The shutter gives.",
        CORRIDOR, NIGHT, "medium", "low_angle", "wide_distorted",
        "One figure, full body, with real weight through the swing.",
        "The shutter and its hinge, the chalk mark visible at the impact point. Sparks bursting outward, small debris thrown.",
        "Debris foreground, figure midground, shutter background. The impact connects all three.",
        light("The impact flash itself, at the hinge", "Hot white-orange",
              "Warm torchlight from below",
              "Hard under the planted foot",
              rim="Hard impact rim on his leading arm and horns",
              cast_shadow="Sharp shadow thrown back and up by the impact flash",
              color_spill="Orange flash across his front, red residue behind"),
        "The hottest panel in the issue. Full impact treatment.",
        "Lower left, clear of the SFX and the impact burst",
        "rectangle", "large", "scene_to_scene",
        ["NEW CORRIDOR plate C - shutter hinge close", LILDEVIL_LAYERS + " - action pose",
         "PROP-service-gate struck state"],
        ["SFX is full house style - large, coloured, angled, overlapping the panel border",
         "The hinge he strikes is the point NeonBlue chalked in panel 20-4",
         "Weight and follow-through are believable",
         "Impact flash lights the scene and every shadow agrees",
         "His devil tail follows the motion arc"],
        blocking=[block(LD, "Centre-right, mid-strike, body extended into the blow", "midground",
                        "Measured against the shutter frame",
                        "One foot planted hard, the other trailing - weight fully committed forward",
                        "At the hinge, locked on the chalk mark",
                        "Both hands driving into the hinge")],
        dialogue=[say(LD, "Precision. Fine. I can do precision.")],
        sfx=["KRAK!"],
        foreground_elements=["Sparks and debris crossing the frame toward camera"],
    ))
    p.append(panel(
        21, 2, "The shutter moves. Everyone's hands are on it.",
        "Four pairs of hands hauling the shutter upward together.",
        CORRIDOR, NIGHT, "medium_close", "low_angle", "normal",
        "Hands and forearms only, from four different characters, at slightly different depths.",
        "The shutter's lower edge, four sets of hands gripping it, metal grinding upward.",
        "Shallow. Hands, shutter edge, dark beyond.",
        light("Floor torches from below", "Warm working white", "Faint red",
              "Hard shadows of the hands on the shutter face",
              color_spill="Warm underlight on every forearm"),
        "Warm, gritty, collective.",
        "None - SFX only",
        "wide", "medium", "action_to_action",
        ["PROP-service-gate shutter detail",
         "character_layers hands detail - neonblue, twotone, static, ash", LILDEVIL_LAYERS],
        ["Four DISTINCT pairs of hands, each identifiable by colour and detail",
         "Hand anatomy correct on all four - highest anatomy risk in the issue",
         "Shutter is visibly moving upward"],
        blocking=[
            block(NB, "Centre-left hands", "foreground", "Hands near life scale",
                  "Out of frame", "Not visible", "Both hands under the shutter edge, hauling"),
            block(LD, "Frame right hands", "foreground", "Slightly nearer camera",
                  "Out of frame", "Not visible", "Both hands under the shutter edge"),
            block(TT, "Centre-right hands", "midground", "Slightly further",
                  "Out of frame", "Not visible", "Both hands on the shutter"),
            block(ASH, "Frame left hands", "midground", "Furthest",
                  "Out of frame", "Not visible", "One hand on the shutter, one bracing the frame"),
        ],
        sfx=["nnnGH - KTCHK"],
    ))
    p.append(panel(
        21, 3, "The payoff. The rescued are the subject.",
        "The shutter is up. The three come out. NeonBlue is at the side, counting them past.",
        CORRIDOR, NIGHT, "wide", "eye_level", "normal",
        "Four figures on one floor - three rescued extras as the subject, NeonBlue secondary at the frame edge.",
        "The raised shutter. The three young festival-goers stepping through into warm light spilling from the grounds beyond. Corridor behind them.",
        "The three walking from background darkness through the midground shutter into foreground warm light. Movement carries the depth.",
        light("Warm light spilling in from the grounds, frame left, ahead of the three",
              "Warm amber - the first restored festival light in several pages",
              "Fading red from the corridor behind",
              "All four figures have contact shadows on the corridor floor",
              rim="Warm rim on the three as they step into it",
              cast_shadow="Shadows thrown back into the corridor, away from the warm source",
              color_spill="Amber on the three, NeonBlue still half in the red"),
        "Warmth returns, and it returns on the rescued rather than on the rescuer.",
        "Upper right, near NeonBlue, clear of all three rescued faces",
        "wide", "large", "action_to_action",
        ["NEW CORRIDOR plate C - shutter open", "character_layers/neonblue",
         TRAPPED + " - walking poses"],
        ["The three rescued figures are the visual SUBJECT, not NeonBlue",
         "All three are the same individuals established in panel 18-6",
         "NeonBlue is at the frame edge, not centred",
         "All four figures have correct contact shadows on one floor",
         "Warm light falls on the three BEFORE it falls on him"],
        blocking=[block(NB, "Frame right, side-on, secondary to the three rescued figures",
                        "midground", "Same ground plane as the three, measured against the shutter frame",
                        "Both feet flat, weight settled, still",
                        "At each of the three in turn as they pass",
                        "One hand out, palm up, counting them past",
                        expression_id="EXP-005-neutral")],
        dialogue=[say(NB, "That's three. That's everyone.")],
    ))
    p.append(panel(
        21, 4, "One quiet beat inside the rescue.",
        "One of the three looking back at NeonBlue as they pass. He does not notice.",
        CORRIDOR, NIGHT, "close", "eye_level", "compressed_telephoto",
        "One small extra face, close, with NeonBlue defocused behind.",
        "The shutter opening, warm light ahead, NeonBlue soft in the background.",
        "Sharp foreground face, defocused background figure.",
        light("Warm from ahead", "Warm amber", "Red residue from behind",
              "Not applicable", color_spill="Amber on the face, red on the hair from behind"),
        "Warm and small. A moment nobody in the story registers.",
        "None - silent panel",
        "square", "small", "subject_to_subject",
        [TRAPPED + " - close face", "character_layers/neonblue defocused"],
        ["The face is one of the three from panel 18-6 - same individual",
         "NeonBlue is defocused and clearly not looking",
         "Silent - no dialogue, no caption"],
    ))
    p.append(panel(
        21, 5, "Close the page on the corridor empty again, and the shutter open.",
        "The corridor, shutter up, nobody in it, the red practical still on.",
        CORRIDOR, NIGHT, "wide", "eye_level", "normal",
        "No cast. Empty corridor with the shutter open.",
        "The service corridor, shutter raised, torches still burning on the floor, nobody present.",
        "Deep, empty, with the open shutter as the focal point.",
        light("Floor torches and the red practical", "Warm white and deep red",
              "Warm spill through the open shutter",
              "Not applicable - nobody present",
              color_spill="Warm through the opening, red overhead"),
        "Empty and warm. The opposite of panel 18-5.",
        "None - silent panel",
        "wide", "medium", "aspect_to_aspect",
        ["NEW CORRIDOR plate C - shutter open, empty"],
        ["Deliberate rhyme with panel 18-5 - same corridor, changed state",
         "Shutter is open", "Silent"],
    ))

    # ---------------- PAGE 22 - AFTER (6) ----------------
    p.append(panel(
        22, 1, "The festival continues in reduced form.",
        "The grounds, half lit, some rides dark, a smaller calmer crowd.",
        GROUNDS, LATE, "extreme_wide", "high_angle", "normal",
        "No identifiable cast. Half-lit grounds.",
        "A DIFFERENT view of the grounds from page 1. Half the lights working. The ferris wheel dark. A smaller, slower crowd. Litter, ended-evening texture.",
        "Single deep plane from a raised angle, warm on one side and dead on the other.",
        light("Restored festival lights on one side only", "Warm amber where alive, nothing where dead",
              "Cool night ambient", "Present under the remaining crowd",
              color_spill="Warm confined to the working half"),
        "Warm and cool coexisting, neither winning. Earned, imperfect.",
        "None - silent panel",
        "wide", "medium", "scene_to_scene",
        ["NEW GROUNDS plate A16 - half-lit, late, different angle from page 1"],
        ["Visibly a DIFFERENT view of the grounds than panel 1-1 - this was the worst legacy failure",
         "The half-lit state is unmistakable - dark rides visible",
         "Crowd is visibly smaller and slower than page 1"],
    ))
    p.append(panel(
        22, 2, "He does not oversell it. The best line in the issue.",
        "NeonBlue sitting on a low barrier with Moodz, Lil Devil standing nearby and unusually still.",
        GROUNDS, LATE, "wide", "eye_level", "normal",
        "Two seated figures and one standing, at three depths. Seated posture is the point - the work is over.",
        "A low barrier at the edge of the half-lit grounds, dark rides behind, warm light from frame left.",
        "Barrier and seated pair midground, standing figure behind, half-lit grounds beyond.",
        light("Restored festival lights from frame left, frame right stays dead",
              "Warm amber left, nothing right", "Cool night ambient",
              "Present under all three, including under the seated feet",
              rim="Warm on the left edges of all three",
              color_spill="Amber on left-facing surfaces, the right half of the panel stays cold"),
        "Warm and cool coexisting. Earned, imperfect.",
        "Upper left, two stacked balloons over the lit grounds",
        "wide", "large", "subject_to_subject",
        ["NEW GROUNDS plate A16 barrier detail", "character_layers neonblue seated, moodz seated",
         LILDEVIL_LAYERS + " - standing still"],
        ["Seated figures have correct contact shadows UNDER THEIR FEET, not under the barrier",
         "Lil Devil is still and quiet, which is new for him",
         "The warm-left cold-right split is unmistakable"],
        blocking=[
            block(NB, "Centre-left, seated on a low barrier", "midground",
                  "Seated - measured against the barrier height",
                  "Seated, both feet flat on the ground, forearms on knees",
                  "Out across the grounds, unfocused", "Hands loose between his knees",
                  expression_id="EXP-005-sleepy"),
            block(MZ, "Beside him on the same barrier, slightly further from camera", "midground",
                  "6 percent smaller - marginally further",
                  "Seated, one foot up on the barrier", "Same direction as NeonBlue",
                  "Hands in pockets"),
            block(LD, "Frame right, standing, further back, unusually still", "background",
                  "Clearly set back from the seated pair",
                  "Both feet, weight even, standing quietly", "Out across the grounds",
                  "Arms at sides"),
        ],
        dialogue=[say(NB, "Stage finale was half-lit. Carousel never came back."),
                  say(NB, "Everyone walked out. That's a good night.")],
    ))
    p.append(panel(
        22, 3, "A small beat confirming the change in him is real.",
        "Moodz glancing sideways at NeonBlue. NeonBlue is not performing.",
        GROUNDS, LATE, "close", "eye_level", "compressed_telephoto",
        "Two heads, tight, at slightly different depths.",
        "Half-lit grounds heavily defocused behind.",
        "Shallow, warm bokeh behind.",
        light("Warm from frame left", "Warm amber", "Cool night", "Not applicable",
              color_spill="Warm on their left profiles"),
        "Warm and quiet.",
        "None - silent panel",
        "rectangle", "small", "moment_to_moment",
        ["character_layers moodz, neonblue close-crop"],
        ["NeonBlue's expression is settled, not bright - the arc has landed",
         "Silent", "Moodz does not say anything, and does not need to"],
        blocking=[
            block(MZ, "Frame left, nearer camera, glancing sideways", "foreground",
                  "Head fills a third of the panel", "Seated, out of frame",
                  "Sideways at NeonBlue", "Not visible"),
            block(NB, "Frame right, slightly further", "midground", "Marginally smaller",
                  "Seated, out of frame", "Out across the grounds, unfocused", "Not visible",
                  expression_id="EXP-005-neutral"),
        ],
    ))
    p.append(panel(
        22, 4, "The Echo answers the choice, after the choice. One segment only.",
        "A hard insert on a dark junction-tower panel where one segment of a larger shape has come alive in cyan.",
        GROUNDS, LATE, "extreme_close", "low_angle", "compressed_telephoto",
        "No characters. Object scale only.",
        "A dark weathered panel high on a junction tower. One segment of a larger geometric shape is lit cyan. The rest is dark and incomplete, and the frame deliberately crops before the shape's full extent.",
        "Flat and tight. A single surface.",
        light("The lit segment is the only source", "Cyan", "None", "Not applicable",
              color_spill="Faint cyan on the surrounding weathered metal"),
        "One small cyan light in near-total black. The quietest and most important image in the issue.",
        "None - SFX only, small, lower right",
        "inset", "medium", "aspect_to_aspect",
        ["PROP-echo-symbol single-segment-lit state", "NEW junction tower panel plate"],
        ["EXACTLY ONE segment is lit - hard season constraint",
         "The full symbol is NEVER visible, and the frame crops before its extent",
         "The lit segment is partial and off-centre",
         "It does not read as a logo or a complete emblem",
         "CONFLICT C-01 - depends on owner ruling"],
        sfx=["tk"],
    ))
    p.append(panel(
        22, 5, "The reader knows something the character does not.",
        "NeonBlue looking up at the tower - at the wrong part of it. Ash nearby, also looking up.",
        GROUNDS, LATE, "medium_wide", "low_angle", "wide_distorted",
        "Two small figures beneath a large structure and a large sky. The scale carries the meaning.",
        "The junction tower rising against a night sky, with the lit cyan segment visible to the reader high on its flank. Warm half-lit festival glow along the bottom edge.",
        "Two small figures on the ground plane, tower rising through the midground, deep night sky behind.",
        light("Warm restored festival light from below and behind camera",
              "Warm amber below, cold blue-black above", "Faint moonlight",
              "Present under both, thrown away from the festival lights",
              rim="Warm rim along both characters' lower silhouettes",
              color_spill="Amber up to about waist height, everything above goes cold"),
        "Warm ground, cold sky, one cyan point. The last light of summer, and something else beginning.",
        "Upper left over open sky",
        "tall", "large", "subject_to_subject",
        ["NEW GROUNDS plate A17 - junction tower, night sky, low angle",
         "character_layers neonblue back view, ash back view",
         "PROP-echo-symbol single-segment-lit state, distant"],
        ["The lit segment is visible to the READER",
         "NeonBlue is demonstrably looking at a DIFFERENT part of the tower",
         "Both characters identifiable from behind - spike crown and silver fringe",
         "Warm-to-cold vertical gradient is present"],
        blocking=[
            block(NB, "Lower-left, small, seen from behind and below, looking up", "midground",
                  "Roughly a quarter of panel height - dwarfed by tower and sky",
                  "Both feet flat, head tilted back",
                  "Up at the tower, but at the WRONG section - away from the lit segment",
                  "Hands at sides"),
            block(ASH, "Lower-right, small, also looking up, slightly further back", "midground",
                  "Marginally smaller than NeonBlue", "Both feet, still",
                  "Up - ambiguous whether toward the lit segment or not",
                  "Hands in hoodie pocket"),
        ],
        dialogue=[say(NB, "It went cyan when I got close. Why would it know me?")],
        foreground_elements=["Ground clutter and barrier silhouettes along the lower edge"],
    ))
    p.append(panel(
        22, 6, "Close the issue and open the season.",
        "Very wide, very far back. The two figures tiny, the tower small, the dark festival huge around them, and one cyan point.",
        GROUNDS, LATE, "extreme_wide", "high_angle", "wide_distorted",
        "Two figures reduced to almost nothing. The scale is the final statement.",
        "The whole half-lit festival from far back and above. The junction tower a small vertical among many. One cyan point on it, tiny but findable. The two figures beneath it barely readable.",
        "Deep and wide. Depth from light density and haze.",
        light("Half the festival's restored lights", "Warm amber where alive",
              "Cool night across everything", "Not readable at this scale",
              color_spill="Warm haze over the working half, cold over the dead half"),
        "Warm and cold, and one cyan point that the reader has to look for.",
        "Lower right caption box",
        "wide", "large", "aspect_to_aspect",
        ["NEW GROUNDS plate A18 - final wide, half-lit, tower with lit segment"],
        ["The cyan point is findable but small - the reader should have to look",
         "Deliberate rhyme with panel 1-1 and the page 11 splash - same site, three states",
         "Final panel of the issue - the strongest image on the page",
         "Exactly one segment still"],
        caption="The question stays.",
    ))

    return p
