"""Panel data for Issue 001 - The Last Light of Summer.

Authoring source for `03_script/panel-script.yaml`. Regenerate the YAML with
`python scripts/production/build_panel_script.py`.

22 story pages, 103 panels. Page structure and rationale: `03_script/page-plan.md`.
Prose direction: `03_script/full-script.md`.
"""

from __future__ import annotations

from scripts.production.build_panel_script import (
    ASH,
    CORRIDOR,
    DUSK,
    GROUNDS,
    LATE,
    LD,
    MZ,
    NB,
    NIGHT,
    NODE,
    SC,
    ST,
    STAGE,
    TT,
    block,
    light,
    panel,
    say,
)

# Shared asset shorthands.
CROWD = "NEW crowd silhouette set"
LILDEVIL_LAYERS = "NEW Lil Devil alpha layer set - does not exist yet"
TRAPPED = "NEW three trapped festival-goer figures"


def build() -> list[dict]:
    p: list[dict] = []

    # ================= PAGE 1 - ARRIVAL (4) =================
    p.append(panel(
        1, 1,
        "Open on the festival at its best, so the reader knows what is about to be lost.",
        "The whole site at golden hour, lights coming on and losing to daylight.",
        GROUNDS, DUSK, "extreme_wide", "high_angle", "wide_distorted",
        "No cast. Scale comes from the ferris wheel and stage against the crowd.",
        "The festival site from a raised angle. Ferris wheel, main stage, booth rows, bunting, dense warm crowd. Nothing is wrong yet.",
        "Foreground bunting, midground rides and stalls, background skyline and low sun.",
        light("Low sun from frame right", "Deep amber", "Cool sky bounce",
              "Long ground shadows from every structure",
              rim="Warm edge on every vertical", cast_shadow="Rides throw long shadows toward camera",
              color_spill="Amber on all right-facing surfaces"),
        "Maximum warmth. The reference image for everything the issue takes away.",
        "Lower-left caption box over open ground",
        "wide", "large", "scene_to_scene",
        ["NEW GROUNDS plate A1 - high wide, golden hour", CROWD],
        ["No cyan anywhere", "Crowd reads as people not texture",
         "Ferris wheel and stage both legible", "Warmest panel in the issue"],
        caption="The last night of summer.",
    ))
    p.append(panel(
        1, 2,
        "Bring the cast in at ground level as a group who arrive together.",
        "The six enter through the main gate in a loose cluster, not a line.",
        GROUNDS, DUSK, "wide", "low_angle", "normal",
        "Six figures at six measurably different depths through a gate arch. Nobody shares a scale.",
        "The main gate arch strung with lights, crowd flowing both ways, booth row beyond.",
        "Gate upright foreground, cast midground through the arch, festival beyond.",
        light("Warm gate lights overhead and behind", "Amber and warm white", "Cool dusk sky",
              "Tight under each foot on packed earth",
              rim="Warm top rim on every head", color_spill="Amber on upward surfaces"),
        "Warm and busy. A good evening starting.",
        "Upper right over the arch, clear of every face",
        "wide", "medium", "scene_to_scene",
        ["NEW GROUNDS plate A2 - gate arch, low", "character_layers all six", CROWD],
        ["All six identifiable", "Six distinct depths",
         "Static already slightly apart", "Every figure has a contact shadow"],
        blocking=[
            block(NB, "Front of the cluster, left of centre", "midground",
                  "Reference figure. Gate arch is 2.4 character heights",
                  "Both feet mid-stride, weight forward", "Ahead into the festival",
                  "One arm already raised, pointing"),
            block(MZ, "Half a step behind NeonBlue", "midground", "6 percent smaller",
                  "Both feet walking", "Ahead, level", "Hands in pockets"),
            block(ST, "Right of the cluster, slightly apart", "midground", "10 percent smaller",
                  "Both feet, hesitating half a step", "Up and off, listening",
                  "One hand near his ear"),
            block(TT, "Centre rear", "midground", "12 percent smaller", "Both feet walking",
                  "Scanning the layout", "Neutral at sides"),
            block(SC, "Left rear", "background", "16 percent smaller", "Both feet, unhurried",
                  "Reading the crowd, not the rides", "Neutral at sides"),
            block(ASH, "Rearmost, trailing", "background", "20 percent smaller",
                  "Both feet, slowest pace", "Down at the ground", "Hands in hoodie pocket"),
        ],
        dialogue=[say(ST, "It smells like burnt sugar and ozone.")],
        foreground_elements=["Gate arch upright crossing the left edge"],
    ))
    p.append(panel(
        1, 3,
        "Establish the main stage as the place everyone will be looking, before it matters.",
        "The main stage across the grounds, countdown board lit above it.",
        STAGE, DUSK, "wide", "low_angle", "compressed_telephoto",
        "No cast. Crowd at the stage base gives it scale.",
        "The stage seen across the grounds. Countdown board showing a long time remaining. Speaker stacks, scaffolding, early crowd.",
        "Compressed by the long lens so the stage reads large while remaining far.",
        light("The stage rig itself", "Cool white and magenta", "Warm ambient from the grounds",
              "Crowd shadows at the stage base", color_spill="Magenta on the nearest crowd"),
        "The cool stage against the warm grounds. Two colour worlds established early.",
        "None - silent panel",
        "wide", "small", "aspect_to_aspect",
        ["NEW STAGE plate A - distant establishing", CROWD],
        ["Countdown board legible", "Stage reads as the centre of attention",
         "No cast member present"],
    ))
    p.append(panel(
        1, 4,
        "End the page on NeonBlue taking in everything at once - the character in one image.",
        "NeonBlue stopped, turning on the spot, delighted.",
        GROUNDS, DUSK, "medium", "low_angle", "wide_distorted",
        "Single figure against sky and light strings.",
        "Light strings converging overhead, festival glow behind, dusk sky above.",
        "Figure midground, light strings foreground crossing above, sky behind.",
        light("Warm string lights above and around", "Amber", "Cool sky",
              "Tight below, softened by multiple sources",
              rim="Warm top rim", cast_shadow="Short radial shadows from several overhead sources",
              color_spill="Amber on every upward surface"),
        "Golden and generous. His baseline.",
        "Upper left over sky",
        "rectangle", "medium", "subject_to_subject",
        ["NEW GROUNDS plate A3 - upward, light strings", "character_layers/neonblue"],
        ["Cyan crown reads as HIS colour, not the system's",
         "Multiple overhead sources give multiple soft shadows",
         "Delight is genuine, not manic"],
        blocking=[block(NB, "Centre, seen from below, turning", "midground",
                        "Head roughly one third panel height",
                        "Both feet pivoting, weight on the ball of one foot",
                        "Up and around, not at anything specific",
                        "Arms slightly out for balance",
                        expression_id="EXP-005-celebrating")],
        dialogue=[say(NB, "Look at all of it.")],
    ))

    # ================= PAGE 2 - VOLUNTEERING (6) =================
    p.append(panel(
        2, 1,
        "NeonBlue volunteers the group before anyone agrees. The first character statement.",
        "NeonBlue walking backwards ahead of the group, counting tasks on his fingers.",
        GROUNDS, DUSK, "medium_wide", "eye_level", "normal",
        "Three figures, three depths, moving in two directions.",
        "Festival path with stalls either side, crowd passing.",
        "NeonBlue near, two behind, stalls receding.",
        light("Stall lights both sides", "Amber and warm magenta", "Dusk sky",
              "Present under all three",
              cast_shadow="Doubled from stalls on both sides",
              color_spill="Amber left, magenta right"),
        "Busy warm. Nobody is worried.",
        "Upper right, two stacked balloons above NeonBlue",
        "wide", "medium", "action_to_action",
        ["GROUNDS plate A2 variant", "character_layers neonblue, moodz, twotone"],
        ["Walking backwards reads clearly", "TwoTone visibly about to speak",
         "Double shadows from two stall rows"],
        blocking=[
            block(NB, "Frame right, walking backwards toward camera-left", "foreground",
                  "Largest, nearest", "Both feet, backwards stride, weight trailing",
                  "At the other two", "Both hands up, counting on fingers",
                  expression_id="EXP-005-smile"),
            block(MZ, "Frame left, walking forward", "midground", "10 percent smaller",
                  "Both feet walking", "At NeonBlue, flat", "Hands in pockets"),
            block(TT, "Behind Moodz", "midground", "14 percent smaller", "Both feet walking",
                  "At NeonBlue", "One hand raised slightly, about to interject"),
        ],
        dialogue=[say(NB, "Food stand needs hands. Lost-kid tent needs hands."),
                  say(NB, "We have twelve hands.")],
    ))
    p.append(panel(
        2, 2,
        "TwoTone registers the problem with volunteering people who have not agreed.",
        "TwoTone, dry, not breaking stride.",
        GROUNDS, DUSK, "medium_close", "eye_level", "normal",
        "Single close figure.",
        "Defocused stall lights behind.",
        "Sharp figure, soft bokeh background.",
        light("Warm from frame left", "Amber", "Cool ambient", "Not applicable - feet out of frame",
              color_spill="Amber on his left half"),
        "Warm, flat, unbothered.",
        "Upper right",
        "rectangle", "small", "action_to_action",
        ["character_layers/twotone close-crop"],
        ["Centred half-black half-white hair correct", "Delivery is dry, not hostile"],
        blocking=[block(TT, "Centre, three-quarter", "foreground",
                        "Head fills a third of the panel", "Walking, feet out of frame",
                        "Level ahead, not at NeonBlue", "Not visible")],
        dialogue=[say(TT, "Which of those did anyone agree to.")],
        approach="approved_layer_composite",
    ))
    p.append(panel(
        2, 3,
        "NeonBlue does not hear it as criticism. His optimism is not calculated.",
        "NeonBlue answers cheerfully, already moving on.",
        GROUNDS, DUSK, "close", "eye_level", "compressed_telephoto",
        "Tight single.",
        "Heavily defocused warm festival light.",
        "Shallow.",
        light("Warm frontal", "Amber", "Weak cool", "Not applicable",
              color_spill="Amber across the face"),
        "Warm and open.",
        "Upper left",
        "square", "small", "action_to_action",
        ["character_layers/neonblue close-crop"],
        ["Under-eye bags visible - required canon", "Smile is warm, not smug"],
        blocking=[block(NB, "Centre, close", "foreground", "Head fills half the panel",
                        "Not visible", "Direct at TwoTone, warm", "Not visible",
                        expression_id="EXP-005-smile")],
        dialogue=[say(NB, "You will.")],
        approach="approved_layer_composite",
    ))
    p.append(panel(
        2, 4,
        "Scarline observes without commenting. Her register established early.",
        "Scarline watching the exchange, already looking past it at the crowd.",
        GROUNDS, DUSK, "medium", "eye_level", "normal",
        "Single figure with crowd behind at two depths.",
        "The crowd flowing past a junction of two paths. Ordinary festival behaviour.",
        "Scarline midground, crowd behind at two depths.",
        light("Overhead strings", "Warm white", "Ambient", "Tight below",
              color_spill="Warm on top surfaces"),
        "Warm, observational.",
        "None - silent panel",
        "rectangle", "small", "subject_to_subject",
        ["GROUNDS plate A4 - path junction", "character_layers/scarline", CROWD],
        ["Scarlet streak on viewer-left - required canon",
         "No facial scar - required canon", "She is watching people, not attractions"],
        blocking=[block(SC, "Frame left, side-on", "midground", "Full figure, mid-height",
                        "Both feet, weight settled, stopped", "Past the group at the crowd flow",
                        "Arms at sides")],
    ))
    p.append(panel(
        2, 5,
        "Ash gets one wordless beat establishing that he is present and paying attention.",
        "Ash at the back, stopped walking, watching NeonBlue rather than the festival.",
        GROUNDS, DUSK, "medium_close", "eye_level", "compressed_telephoto",
        "Single close figure.",
        "Defocused festival warmth behind.",
        "Shallow.",
        light("Warm from frame right", "Amber", "Cool ambient", "Not applicable",
              color_spill="Warm rim on his silver-white fringe"),
        "Warm but quiet.",
        "None - silent panel",
        "rectangle", "small", "subject_to_subject",
        ["character_layers/ash close-crop"],
        ["Silver-white fringe and half-lidded eyes correct", "Silent panel",
         "He is watching NeonBlue, not the festival"],
        blocking=[block(ASH, "Centre, half-turned", "foreground",
                        "Head fills a third of the panel", "Standing still, feet out of frame",
                        "At NeonBlue off frame right, half-lidded", "Hands in hoodie pocket")],
        approach="approved_layer_composite",
    ))
    p.append(panel(
        2, 6,
        "Close the page on the group splitting up, which is what makes the blackout dangerous.",
        "The six moving apart into the crowd along diverging paths.",
        GROUNDS, DUSK, "wide", "high_angle", "normal",
        "Six figures dispersing along diverging vectors, scale falling off with distance.",
        "A wide path junction from above, crowd dense, paths leading to different zones.",
        "Single deep ground plane from above. Depth from scale and crowd density.",
        light("Overhead strings throughout", "Amber", "Dusk sky",
              "Short shadows directly below each figure",
              color_spill="Warm on all upward surfaces"),
        "Warm, wide, slightly lonely already.",
        "Lower right caption box",
        "wide", "large", "scene_to_scene",
        ["NEW GROUNDS plate A5 - path junction from above", "character_layers all six", CROWD],
        ["Six diverging directions readable", "Static looking back is visible",
         "The issue's only piece of retrospective narration"],
        blocking=[
            block(NB, "Centre, moving away from camera", "midground", "Mid-scale",
                  "Both feet walking away", "Ahead", "One hand raised in parting"),
            block(MZ, "Frame left, diverging", "midground", "Similar to NeonBlue",
                  "Both feet walking", "Ahead", "Hands in pockets"),
            block(TT, "Frame right, diverging", "midground", "Similar to NeonBlue",
                  "Both feet walking", "Ahead", "Neutral at sides"),
            block(ST, "Frame right rear", "background", "Smaller", "Both feet, slower",
                  "Back over his shoulder", "One hand near his ear"),
            block(SC, "Frame left rear", "background", "Smaller", "Both feet walking",
                  "Ahead", "Neutral at sides"),
            block(ASH, "Centre rear, slowest", "background", "Smallest", "Both feet, slow",
                  "Down", "Hands in hoodie pocket"),
        ],
        caption="They split up. It seemed like a good idea.",
    ))

    # ================= PAGE 3 - THE FESTIVAL WORKS (5) =================
    p.append(panel(
        3, 1,
        "Show the festival functioning so its failure has something to fail from.",
        "The food stand at full tilt, NeonBlue behind the counter, genuinely helping.",
        GROUNDS, DUSK, "medium_wide", "eye_level", "normal",
        "One figure behind a counter with queue silhouettes in the foreground.",
        "A busy food stand interior, heat lamps, steam, a queue pressing at the counter.",
        "Queue silhouettes foreground, counter and NeonBlue midground, stand interior behind.",
        light("Heat lamps above the counter", "Hot orange", "Warm ambient",
              "Under the counter edge and his feet",
              color_spill="Orange on his face and forearms"),
        "Hot, busy, cheerful.",
        "Upper right, clear of the queue",
        "wide", "medium", "scene_to_scene",
        ["NEW GROUNDS plate A6 - food stand interior", "character_layers/neonblue", CROWD],
        ["He is actually working, not posing", "Steam and heat haze present",
         "Queue reads as individual people"],
        blocking=[block(NB, "Centre behind the counter", "midground",
                        "Counter is at his chest height",
                        "Both feet, weight shifting between them, working",
                        "Down at what his hands are doing", "Both hands busy with an order",
                        occlusion="Counter and queue heads cross his lower body",
                        expression_id="EXP-005-smile")],
        dialogue=[say(NB, "Two more coming up.")],
        foreground_elements=["Queue silhouettes across the lower third"],
    ))
    p.append(panel(
        3, 2,
        "Introduce Lil Devil by having him arrive where he was not invited.",
        "Lil Devil leaning on the counter from the customer side, already bored.",
        GROUNDS, DUSK, "two_shot", "eye_level", "normal",
        "Two figures separated by a counter, at slightly different depths.",
        "The counter from a side angle, stand lights behind NeonBlue, festival dark beyond Lil Devil.",
        "Two-plane. The counter is the dividing line.",
        light("Stand lamps from behind NeonBlue", "Hot orange", "Cool festival ambient",
              "Present on both, differing in hardness",
              rim="Orange rim on Lil Devil's horns from behind the counter",
              color_spill="Orange on NeonBlue, cooler on Lil Devil"),
        "Warm inside the stand, cooler outside it. Lil Devil's red is the hottest note.",
        "Upper centre, one balloon",
        "rectangle", "medium", "subject_to_subject",
        ["GROUNDS plate A6 side angle", "character_layers/neonblue", LILDEVIL_LAYERS],
        ["Lil Devil matches approved canon - red horns, red outfit, purple eyeshadow, tail",
         "The counter genuinely separates them in depth", "Devil tail does not clip the edge"],
        blocking=[
            block(LD, "Frame right, leaning on the counter", "foreground",
                  "Nearer camera, 8 percent larger than NeonBlue",
                  "Both feet, weight on the counter through his forearms",
                  "Sideways at NeonBlue", "Both forearms flat on the counter"),
            block(NB, "Frame left, behind the counter", "midground", "Set back by the counter depth",
                  "Both feet, working", "At Lil Devil", "One hand still holding an order"),
        ],
        dialogue=[say(LD, "You volunteered for this.")],
    ))
    p.append(panel(
        3, 3,
        "Lil Devil states his worldview once, comically, so it can cost something later.",
        "Lil Devil gestures at the queue with contempt.",
        GROUNDS, DUSK, "medium_close", "low_angle", "normal",
        "Single figure, low angle to make him bigger than he is.",
        "Festival lights behind him, queue out of focus.",
        "Shallow, with the queue softly behind.",
        light("Festival lights behind and above", "Warm magenta", "Weak",
              "Not applicable", rim="Magenta rim on horns and shoulders",
              color_spill="Magenta on his upper edges"),
        "Hot red against magenta. He is enjoying himself.",
        "Upper left",
        "rectangle", "small", "action_to_action",
        [LILDEVIL_LAYERS],
        ["Low angle does not distort him off-model", "Expression is amused, not cruel"],
        blocking=[block(LD, "Centre, low angle", "foreground", "Head fills a third of the panel",
                        "Standing, feet out of frame", "Off at the queue",
                        "One hand thrown toward the queue")],
        dialogue=[say(LD, "There is a shorter way to get food.")],
        approach="approved_layer_composite",
    ))
    p.append(panel(
        3, 4,
        "NeonBlue's answer shows his optimism is a working method, not naivety.",
        "NeonBlue passing an order over the counter without looking up.",
        GROUNDS, DUSK, "medium_close", "eye_level", "normal",
        "Single figure with hands as the focus.",
        "Counter surface, order in transit, warm lamp above.",
        "Shallow. Hands and counter foreground, his face midground.",
        light("Heat lamp directly above", "Hot orange", "Warm bounce off the counter",
              "Hard shadow under the order on the counter",
              color_spill="Orange on the tops of his hands and head"),
        "Hot and close.",
        "Upper right",
        "rectangle", "small", "action_to_action",
        ["GROUNDS plate A6 counter detail", "character_layers/neonblue"],
        ["Hands are the focus and must be believable - highest anatomy risk on the page",
         "Overhead lamp casts a hard shadow under the order"],
        blocking=[block(NB, "Frame left, hands extended across the counter", "midground",
                        "Hands near life scale against the order",
                        "Both feet, leaning forward from the hips",
                        "Down at his hands", "Both hands passing an order across",
                        expression_id="EXP-005-neutral")],
        dialogue=[say(NB, "There is. It has a longer queue.")],
    ))
    p.append(panel(
        3, 5,
        "End the page with the festival at its loudest, immediately before the first fault.",
        "Wide across the busiest stretch of the grounds, everything working.",
        GROUNDS, "Dusk, last light gone", "extreme_wide", "eye_level", "wide_distorted",
        "No identifiable cast. Crowd density gives the scale.",
        "The busiest stretch of the grounds. Every booth lit, rides turning, crowd shoulder to shoulder.",
        "Deep. Crowd foreground, booths midground, ferris wheel and sky behind.",
        light("Every booth and ride", "Amber, magenta, warm white", "None needed - saturated",
              "Dense overlapping crowd shadows",
              color_spill="Every surface carries several colours"),
        "The busiest, brightest panel in the issue. Peak festival.",
        "None - silent panel",
        "wide", "medium", "aspect_to_aspect",
        ["NEW GROUNDS plate A7 - busiest stretch, full night lighting", CROWD],
        ["Peak brightness in the issue - later pages measure against this",
         "No cyan in the festival palette", "Crowd reads as individuals at print size"],
    ))

    from scripts.production import issue001_panels_b, issue001_panels_c

    p += issue001_panels_b.build()
    p += issue001_panels_c.build()
    return p
